01GRANELES LIQUIDOS PETROLIFEROS                        
02GRANELES LIQUIDOS NO PETROLIFEROS                     
03GAS NATURAL                                           
04GRANELES SOLIDOS POR INST. ESPECIAL                   
05GRANELES SOLIDOS SIN INST. ESPECIAL                   
10CARGA GENERAL                                         
11CARGA GENERAL CONTENERIZADA                           
12CARGA GENERAL EN PALETS                               
13CARGA GENERAL OTRA UNITIZACION                        
14CARGA GENERAL SUELTA                                  
15PLATAFORMAS                                           
16CAMIONES                                              
17REMOLQUES                                             
20CONTENEDORES 20 PIES                                  
21CONTENEDORES < 20 PIES                                
35CONTENEDORES (> 20' Y < 40')                          
40CONTENEDORES 40 PIES                                  
45CONTENEDORES > 40 PIES                                