AEABUABU AL BUKHOOSH                    05
AEAJMAJMAN                              05
AEAUHABU DHABI                          05
AEDASDAS ISLAND                         05
AEDXBDUBAI                              05
AEFJRFUJAIRAH (AL-FUJAIRAH)             05
AEJEAJEBEL ALI                          05
AEJEDJEBEL DHANNA                       05
AEKHLMINA KHALIFA (ABU DHABI)           05
AEKLFKHOR AL FAKKAN                     05
AEMUBMUBAREK TERMINAL                   05
AEPRAPORT RASHID                        05
AEQIVUMM AL QAIWAIN                     05
AEQIWUMM AL QAIWAIN                     05
AERKTRAS AL KHAIMAH                     05
AERUWRUWAIS                             05
AESHJSHARJAH                            05
AGANUST JOHNS                           17
AGBBQBARBUDA                            17
AGSJOST JOHN'S                          17
AIBLPBLOWING POINT                      17
AIFORTHE FOREST                         17
AIROATHE ROAD                           17
AISOMSOMBRERO                           17
ALDRZDURRES (DURAZZO)                   03
ANAUAARUBA                              17
ANCRBCARACAS BAY, CURACAO               17
ANCURCURACAO                            17
ANKRAKRALENDIJK, BONAIRE                17
ANORJORANJESTAD, ARUBA                  17
ANPHIPHILIPSBURG                        17
ANSXMST MAARTEN                         17
ANWILWILLEMSTAD, CURACAO                17
AOAZZAMBRIZ                             11
AOBDTBAIA DOS TIGRES                    11
AOBUGBENGUELA                           11
AOCABCABINDA                            11
AOLAALANDANA                            11
AOLADLUANDA                             11
AOLOBLOBITO                             11
AOMSZMOCAMEDES (MOSSAMEDES)             11
AOPLEPORTO ALEXANDRE                    11
AOSOQSOYO-QUINFUQUENA TERMINAL          11
AOTAKTAKULA TERMINAL                    11
ARBHIBAHIA BLANCA                       18
ARBUEBUENOS AIRES                       18
ARCMPCAMPANA                            18
ARCNQCORRIENTES                         18
ARFMAFORMOSA                            18
ARLPSLAS PALMAS                         18
ARMDQMAR DEL PLATA                      18
ARNECNECOCHEA-QUEQUEN                   18
ARPMYPUERTO MADRYN                      18
ARPRAPARANA                             18
ARPUDPUERTO DESEADO                     18
ARQQNQUEQUEN                            18
ARRGARIO GRANDE                         18
ARROSROSARIO                            18
ARSAESAN ANTONIO ESTE                   18
ARSFNSANTA FE                           18
ARSLOSAN LORENZO                        18
ARSPDSAN PEDRO                          18
ARTUCTUCUMAN                            18
ARUSHUSHUAIA                            18
ARXPDSAN PEDRO                          18
ARZAEZARATE                             18
ASPPGPAGO PAGO                          09
AUABPABBOT POINT                        09
AUADLADELAIDE, SA                       09
AUBELBELL BAY                           09
AUBNEBRISBANE, QL                       09
AUBRTBATHURST ISLAND, NT                09
AUBTBBOTANY BAY, NS                     09
AUBURBURNIE, TS                         09
AUBWTBURNIE                             09
AUCBRCANBERRA                           09
AUCNSCAIRNS, QL                         09
AUDAMDAMPIER, WA                        09
AUDRWDARWIN, NT                         09
AUFISFISHERMAN ISLAND                   09
AUFREFREMANTLE, WA                      09
AUGETGERALDTON, WA                      09
AUGLTGLADSTONE, QL                      09
AUHBAHOBART, TS                         09
AUJFMFREMANTLE                          09
AULSTLAUNCESTON, TS                     09
AUMELMELBOURNE, VI                      09
AUMKYMACKAY, QL                         09
AUNTLNEWCASTLE, NS                      09
AUPAEPORT ADELAIDE                      09
AUPERPERTH, WA                          09
AUPKLPORT KEMBLA, NS                    09
AUPORPORT MELBOURNE                     09
AUSMTSALADIN MARINE TERMINAL            09
AUSYDSYDNEY, NS                         09
AUTSVTOWNSVILLE, QL                     09
AUWEPWESTERNPORT, VI                    09
AWAUAARUBA                              17
AWBARBARCADERA                          17
AWORJORANJESTAD                         17
AWSNLSINT NICOLAAS                      17
AZBAKBAKU                               03
BBBGIBRIDGETOWN                         17
BDBZLBARISAL                            06
BDCGPCHITTAGONG                         06
BDCHLCHALNA                             06
BDMGLMONGLA                             06
BDMONCHALNA-MONGLA                      06
BDNARNARAYANGANJ                        06
BEANRANTWERPEN                          01
BEBRUBRUXELLES (BRUSSEL)                01
BEEEKEEKLO                              01
BEGNEGENT                               01
BEGNKGENK                               01
BEHEXHEMIKSEM                           01
BEKOUKALLO                              01
BETESTESSENDERLO                        01
BEVVIVIESVILLE                          01
BEWARWAREGEM                            01
BEWLBWILLEBROEK                         01
BEZEEZEEBRUGGE                          01
BEZELZELZATE                            01
BFOUAOUAGADOUGOU                        11
BGAKHAKHOTOPOL                          03
BGBALBALTCHIK                           03
BGBOJBURGAS                             03
BGLOMLOM                                03
BGOREORICHOVO                           03
BGRDURUSE                               03
BGSOMSOMOVIT                            03
BGVARVARNA                              03
BGVAZVARNA-ZAPAD                        03
BGVIDVIDIN                              03
BHBAHBAHRAIN                            05
BHKBSKHALIFA BIN SALMAN PT              05
BHMANMANAMA                             05
BHMINMINA SULMAN                        05
BHRASAL MUTAE                           05
BHSITSITRA                              05
BJCOOCOTONOU                            11
BJPTNPORT NOVO                          11
BMBDAHAMILTON                           13
BMFPTFREEPORT                           13
BNBTNBRUNEI TOWN                        07
BNBWNBANDAR SERI BEGAWAN                07
BNLUMLUMUT                              07
BNMUAMUARA                              07
BNTASTANJONG SALIRONG                   07
BOGUQGUAQUI                             19
BOPBUPUERTO BUSCH                       19
BOPSZPUERTO SUAREZ                      19
BORIBRIBERALTA                          19
BOTDDTRINIDAD                           19
BRADRANGRA DOS REIS, RJ                 18
BRANTANTONINA, PR                       18
BRARBARATU, BA                          18
BRBELBELEM, PA                          18
BRBNUBLUMENAU, SC                       18
BRBPSPORTO SEGURO                       18
BRFLNFLORIANOPOLIS, SC                  18
BRFORFORTALEZA, CE                      18
BRIOAITAPOA, SC                         18
BRIQIITAQUI                             18
BRITJITAJAI, SC                         18
BRITQITAQUI/SAO LUIZ                    18
BRMAOMANAUS, AM                         18
BRMCPMACAPA, AP                         18
BRMCZMACEIO, AL                         18
BRMVTPort: BRMVT                        99
BRNATNATAL, RN                          18
BRNVTNAVEGANTES                         18
BRPECPECEM                              18
BRPMAPONTA DA MADEIRA                   18
BRPNGPARANAGUA, PR                      18
BRPOAPORTO ALEGRE, RS                   18
BRPOUPONTA DO UBU                       18
BRPVHPORTO VELHO, RO                    18
BRQFSSAO FRANCISO DO SUL                18
BRRECRECIFE, PE                         18
BRRIGRIO GRANDE, RS                     18
BRRIORIO DE JANEIRO, RJ                 18
BRSANSANTANA                            18
BRSAOSAO PAULO, SP                      18
BRSEPSEPETIBA                           18
BRSFSSAO FRANCISCO DO SUL, SC           18
BRSLZSAO LUIS, MA                       18
BRSPBPORT OF ITAGUAI                    18
BRSSASALVADOR, BA                       18
BRSSZSANTOS, SP                         18
BRSTMSANTAREM, PA                       18
BRSUASUAPE                              18
BRTUBTUBARAO, SC                        18
BRVCOCONDE                              18
BRVIXVITORIA, ES                        18
BRVLCVILA DO CONDE                      18
BSASDANDROS TOWN, ANDROS ISLAND         17
BSCELCAPE ELEUTHERA, ELEUTHERA          17
BSFPOFREEPORT, GRAND BAHAMA             17
BSNASNASSAU, NEW PROVIDENCE ISLAND      17
BURGNRANGOON                            07
BZBZEBELIZE CITY                        17
C    Port: C                            99
CAAALALERT BAY, BC                      16
CAAVOAVONDALE, NS                       14
CABADBADDECK, NS                        14
CABARBAY ROBERTS                        14
CABCOBAIE COMEAU, QU                    14
CABUIBURIN, NF                          14
CACALCALGARY                            14
CACAMCAMPBELL RIVER, BC                 16
CACBCCome By Chance                     14
CACBGPort: CACBG                        ZZ
CACBKCORNER BROOK, NF                   14
CACHICHICOUTIMI                         14
CACHVCHURCHILL, MN                      14
CACRTCARTIER, OT                        14
CACWLCORNWALL, OT                       14
CADELPort: CADEL                        ZZ
CADWLDINGWALL, NS                       14
CAGALCAMBRIDGE (EX GALT), OT            14
CAGGWGEORGETOWN, OT                     14
CAHALHALIFAX, NS                        14
CAHAMHAMILTON, OT                       14
CAKINKINGSTON, OT                       14
CAKTCKITCHENER, OT                      14
CALACPort: CALAC                        ZZ
CALADLADYSMITH, BC                      16
CALTWLISTOWEL, OT                       ZZ
CAMTRMONTREAL, QU                       14
CANWENEW WESTMINSTER, BC                16
CAOAKOAKVILLE, OT                       14
CAOSHOSHAWA, OT                         14
CAPAPAGUATHUNA (PORT AU PORT)           14
CAPCAPORT CARTIER, QU                   14
CAPMEPORT MENIER, QU                    14
CAPOIPOINTE CLAIRE                      14
CAPREPRESCOTT, OT                       14
CAPSTPORT STANLEY, OT                   14
CAQUEQUEBEC, QU                         14
CASCAPort: CASCA                        ZZ
CASJBSAINT JOHN, NB                     14
CASJFST JOHNS, NF                       14
CASLWPort: CASLW                        ZZ
CASORSOREL, QU                          14
CASSMSAULT STE MARIE, OT                14
CASTCPort: CASTC                        ZZ
CATHUTHUNDER BAY, OT                    14
CATORTORONTO, OT                        14
CATRRTHREE RIVERS (TROIS-RIVIERES), QU  14
CAVANVANCOUVER, BC                      16
CAVLFVALLEYFIELD, QU                    14
CAWELWELLAND, OT                        14
CAWNDWINDSOR, OT                        14
CAWNPWINNIPEG, MN                       14
CDANGANGO-ANGO                          11
CDBNWBANANA                             11
CDBOABOMA                               11
CDFIHKINSHASA                           11
CDMATMATADI                             11
CDMKLMAKALA                             11
CGDJEDJENO TERMINAL                     11
CGMOSMOSSAKA                            11
CGOUEOUESSO                             11
CGOYOOYO                                11
CGPNRPOINTE NOIRE                       11
CHBSLBASEL                              02
CIABJABIDJAN                            11
CISPYSAN PEDRO                          11
CKARUARUTUNGA                           09
CLANFANTOFAGASTA                        19
CLARIARICA                              19
CLCCPTALCAHUANO/CONCEPCION              19
CLCHBCHACABUCO                          19
CLCNLCORONEL                            19
CLCNRCHANARAL                           19
CLCNXCABO NEGRO                         19
CLCPOCOPIAPO                            19
CLCQQCOQUIMBO                           19
CLDCHDALCAHUE                           19
CLGYCGUAYACAN                           19
CLIQQIQUIQUE                            19
CLLQNLIRQUEN                            19
CLMJSMEJILLONES                         19
CLOVLOVALLE                             19
CLPAGPUERTO ANGAMOS                     19
CLPMCPUERTO MONTT                       19
CLPNTPUERTO NATALES                     19
CLPTEQUELLON (PUERTO QUELLON)           19
CLPUQPUNTA ARENAS                       19
CLQMCQUEMCHI                            19
CLQRCRANCAGUA                           19
CLSAISAN ANTONIO                        19
CLSVESAN VICENTE                        19
CLTALTALCAHUANO                         19
CLTHOTALCAHUANO                         19
CLTLXTALCA                              19
CLVAPVALPARAISO                         19
CLZOSOSORNO                             19
CLZUDANCUD                              19
CMDLADOUALA                             11
CMGOUGAROUA                             11
CMLITLIMBOH TERMINAL                    11
CNAQGANQING                             08
CNBAOBAOSHANMATOU                       08
CNBASBASUO                              08
CNBAYBAYUQUAN                           08
CNBEHBEIHAI                             07
CNBHYBEIHAI                             08
CNBJOBEIJIAO                            08
CNCANGUANGZHOU                          08
CNCGQCHANGCHUN                          08
CNCGUCHANGSHU                           08
CNCHECHENGAO                            08
CNCHSCHUANSHAN                          08
CNCHZCHUZHOU                            08
CNCJGCAOJING                            08
CNCKGCHONGQING                          08
CNCLJCHENGLINJI                         08
CNCNHCONGHUA                            08
CNCOZCHAOZHOU                           08
CNCQGPort: CNCQG                        99
CNCTUCHENGDU                            08
CNCWNCHIWAN                             08
CNCZXCHANGZHOU                          08
CNDAADAGANG                             08
CNDALDALI                               08
CNDCBDA CHAN BAY                        08
CNDDGDANDONG                            08
CNDJTDONGJIAOTOU                        08
CNDLCDALIAN                             08
CNDOUDOUMEN                             08
CNDSNDONGSHAN                           08
CNFAGFUGANG                             08
CNFANFANGCHENG                          08
CNFCNFANGCUN                            08
CNFOCFUZHOU                             08
CNFOSFOSHAN                             08
CNFUGFUQING                             08
CNFUJFUJIN                              08
CNFUYFUYUAN                             08
CNFZPFUZHOU PT                          08
CNGAOGAOGANG                            08
CNGASGAOSHA                             08
CNGAYGAOYAO                             08
CNGBTGUANGBAOTONG                       08
CNGHIGUANGHAI                           08
CNGLNGAOLAN                             08
CNGOMGAOMING                            08
CNGONGAOLAN                             08
CNGUGGUIGANG                            08
CNHAIHAIAN                              08
CNHAKHAIKOU                             08
CNHCNHUACHUAN                           08
CNHKGHONG KONG                          08
CNHKUHUKOU                              08
CNHMEHAIMEN                             08
CNHMNHUMEN                              08
CNHNHHUANGHUA                           08
CNHOPHUANGPU OLD PORT                   08
CNHPUPort: CNHPU                        99
CNHRBHARBIN                             08
CNHSIHUANGSHI                           08
CNHSNHESHAN                             08
CNHSTHEISHANTOU                         08
CNHUAHUANGPU                            08
CNHUDHUA DU                             08
CNHUIHUIZHOU                            08
CNHUMHUMA                               08
CNHUNHUANGPU NEW PORT                   08
CNHYNHUANGYAN                           08
CNJAYJIAYIN                             08
CNJGYJIANGYIN                           08
CNJHGJINGHONG                           08
CNJIAJIANGYIN                           08
CNJINJINGTANG (TANGSHAN)                08
CNJIUJIUJIANG                           08
CNJMNJIANGMEN                           08
CNJNZJINZHOU                            08
CNJXNJIAO XIN                           08
CNJZUJIUZHOU                            08
CNKWEGUIYANG                            08
CNLIHLIANHUASHAN                        08
CNLKULONGKOU, SHANDONG                  08
CNLSHLUSHUN                             08
CNLSILANSHI                             08
CNLSNLANSHAN                            08
CNLUULELIU                              08
CNLYGLIANYUNGANG                        08
CNLZULUZHOU                             08
CNMAAMAANSHAN                           08
CNMACMACAU                              08
CNMAWMAWEI                              08
CNMWNMAWAN                              08
CNNAHNANHAI                             08
CNNANNANAO                              08
CNNBONINGBO                             08
CNNGBNINGBO                             08
CNNJGPort: CNNJG                        99
CNNKGNANJING                            08
CNNSANANSHA                             08
CNNTGNANTONG                            08
CNQINPort: CNQIN                        99
CNQLNQINGLAN                            08
CNQZHQINZHOU                            08
CNQZJQUANZHOU                           08
CNROQRONGQI                             08
CNRZHRIZHAO                             08
CNSBUSANBU                              08
CNSDGSHUIDONG                           08
CNSHASHANGHAI                           08
CNSHDSHIDAO                             08
CNSHEPort: CNSHE                        99
CNSHKSHEKOU                             08
CNSHOSHAJIAO                            08
CNSHPQINHUANGDAO                        08
CNSHUSHEKOU                             08
CNSINSHATIAN                            08
CNSJQSANSHUI                            08
CNSTOPort: CNSTO                        99
CNSUDSHUNDE                             08
CNSWASHANTOU                            08
CNSWESHANWEI                            08
CNSXJSANSHAN                            08
CNSZPSHENZHEN PT                        08
CNSZXSHENZHEN                           08
CNTAGTAICANG                            08
CNTAOQINGDAO                            08
CNTAPTAIPING                            08
CNTIZTAIZHOU                            08
CNTOJTONGJIANG                          08
CNTSNTIANJIN                            08
CNTXGTIANJINXINGANG                     08
CNTZOTAIZHOU                            08
CNWAIWAIHAI                             08
CNWAZWANZAI                             08
CNWEIWEIHAI                             08
CNWENPort: CNWEN                        99
CNWHIWUHU                               08
CNWHNWUHAN                              08
CNWNZWENZHOU                            08
CNWUHWUHAN                              08
CNWUZWUZHOU                             08
CNXABXINFENG                            08
CNXGGXINGANG (TANGGU)                   08
CNXIAXISAN                              08
CNXIHXIAHAI                             08
CNXILXIAOLAN                            08
CNXINXINHUI                             08
CNXITXINTANG                            08
CNXMNXIAMEN (XIAN)                      08
CNXNAXINSHA                             08
CNXXYXIANGYU TERMINAL/ XIAMEN           08
CNYANYANGSHAN                           08
CNYGZYINGZI                             08
CNYICYICHANG                            08
CNYIKYINGKOU                            08
CNYJIYANGJIANG                          08
CNYNTYANTAI                             08
CNYPGYANGPU                             08
CNYQSBEIJIAO                            08
CNYTNYANTIAN                            08
CNYZHYANGZHOU                           08
CNZAPZHAPU                              08
CNZHAZHANJIANG                          08
CNZHEZHENJIANG, JIANGSU                 08
CNZJGZHANGJIAGANG                       08
CNZOSZHOUSHAN                           08
CNZQGZHAOQING                           08
CNZSNZHONGSHAN                          08
CNZUHZHUHAI                             08
CNZZUZHANGZHOU                          08
COBAQBARRANQUILLA                       17
COBUNBUENAVENTURA                       19
COCRCCARTAGO                            17
COCTGCARTAGENA                          17
COEJABARRANCABERMEJA                    17
COLETLETICIA                            17
COPBOPUERTO BOLIVAR                     17
COPUCPUERTO COLOMBIA                    17
CORCHRIOHACHA                           17
COSMRSANTA MARTA                        17
COTCOTUMACO                             19
COTRBTURBO                              17
CRCALCALDERA                            17
CRCYLCOYOL                              17
CRGLFGOLFITO                            17
CRJICJICARAL                            17
CRLIOPUERTO LIMON                       17
CRMOBMOIN BAY (PUERTO LIMON)            17
CRMUEMUELLE DE SAN CARLOS               17
CRPASPUNTARENAS                         17
CRSJOSAN JOSE                           17
CSBARBAR                                03
CUANTANTILLA                            17
CUCAICAIBARIEN                          17
CUHAVHABANA                             17
CUMARMARIEL                             17
CUSCUSANTIAGO DE CUBA                   17
CVMINMINDELO                            11
CVPGRPORTO GRANDE                       11
CVRAIPRAIA                              11
CVVXESAO VICENTE                        11
CYAKTAKROTIRI                           03
CYFMGFAMAGUSTA                          03
CYKARKARAVOSTASSI                       03
CYLATLATCHI                             03
CYLCALARNACA                            03
CYLMSLIMASSOL                           03
CYNICNICOSIA                            03
CYVASVASSILIKO                          03
CYZERZEROS                              03
CZHSAHRENSKO                            03
DEAAHAACHEN                             01
DEABHABBEHAUSEN                         01
DEAGBAUGSBURG                           01
DEAMBAMBERG                             01
DEBBGBRANDENBURG                        01
DEBERBERLIN                             01
DEBKEBRAKE                              01
DEBONBONN                               01
DEBRBBRUNSBUTTEL                        01
DEBREBREMEN                             01
DEBRMBRAMSCHE                           01
DEBRVBREMERHAVEN                        01
DEBSABAD SACKINGEN                      01
DECUXCUXHAVEN                           01
DEDRSDRESDEN                            01
DEDTMDORTMUND                           01
DEDUIDUISBURG                           01
DEDUSDüSSELDORF                         01
DEEMEEMDEN                              01
DEEMMEMMERICH                           01
DEESSESSEN                              01
DEFRAFRANKFURT                          01
DEFREFRESENBURG                         01
DEGERGERMERSHEIM                        01
DEGRDGREIFSWALD                         01
DEGREGREETSIEL                          01
DEGUGGüNZBURG                           01
DEHAJHANNOVER                           01
DEHAMHAMBURG                            01
DEHANHAMELN                             01
DEHASHASSFURT                           01
DEHBUHARBURG                            01
DEHMMHAMM                               01
DEHSIHEIDESHEIM                         01
DEITZITZEHOHE                           01
DEKAEKARLSRUHE                          01
DEKEHKEHL                               01
DEKELKIEL                               01
DEKOLKOLLMAR                            01
DEKREPort: DEKRE                        ZZ
DELBCLUBECK                             01
DELDHLANDSHUT                           01
DELEELEER                               01
DELEVLEVERKUSEN                         01
DELUHLUDWIGSHAFEN                       01
DEMELMELDORF                            01
DEMHGMANNHEIM                           01
DEMRSMARIENSIEL                         01
DENHANORDENHAM                          01
DENHNNORDHORN                           01
DENSSNEUSS                              01
DEOBEOBERHAUSEN                         01
DEPAPPAPENBURG                          01
DEPASPASSAU                             01
DEPEIPEINE                              01
DERHBRHEINBERG                          01
DERSKROSTOCK                            01
DESAASAARLOUIS                          01
DESPISPIECKEROOG I.                     01
DESTASTADE                              01
DESTLSTRALSUND                          01
DETRITRIER                              01
DEWOEWORTH                              01
DEWORWORMS                              01
DEWTMWERTHEIM                           01
DEWUEWURZBURG                           01
DEWVNWILHELMSHAVEN                      01
DEZLTZELTINGEN-RACHTIG                  01
DJJIBDJIBOUTI                           04
DKAABAABENRAA                           01
DKAALAALBORG                            01
DKAARAARHUS                             01
DKBRBBRABRAND                           01
DKCPHKOBENHAVN                          01
DKEBJESBJERG                            01
DKFDHFREDERIKSHAVN                      01
DKFDVFREDERIKSVARK                      01
DKFRCFREDERICIA                         01
DKGREGRENAA                             01
DKHORHORSENS                            01
DKKALKALUNDBORG                         01
DKKOGKOGE                               01
DKKOLKOLDING                            01
DKNBGNYBORG                             01
DKNVDNASTVED                            01
DKODEODENSE                             01
DKSVESVENDBORG                          01
DKVEJVEJLE                              01
DMRSUROSEAU                             17
DOBANBANI                               17
DOBCCBOCA CHICA                         17
DOBRXBARAHONA                           17
DOCAUCAUCEDO                            17
DOCBJCABO ROJO                          17
DOCIUCIUDAD TRUJILLO                    17
DOHAIHAINA (RIO HAINA)                  17
DOHIGHIGUEY                             17
DOLRMLA ROMANA                          17
DOMANMANZANILLO                         17
DOPOPPUERTO PLATA                       17
DOSDQSANTO DOMINGO                      17
DZAAEANNABA (FORMERLY BONE)             10
DZALGALGER                              10
DZAZWARZEW                              10
DZBJABEJAIA (FORMERLY BOUGIE)           10
DZBSFBENISAF                            10
DZDELDELLYS                             10
DZDJEDJEN-DJEN                          10
DZDJIDJIDJELLI                          10
DZGHAGHARDAIA                           10
DZGHZGHAZAOUET                          10
DZMOSMOSTAGANEM                         10
DZORNORAN                               10
DZSKISKIKDA                             10
DZTENTENES                              10
EAGP Port: EAGP                         99
ECAYOPUERTO AYORA, ISLA SANTA CRUZ      19
ECBHABAHIA DE CARAQUES                  19
ECCATCALETA TAGUS                       19
ECCUECUENCA                             19
ECDUNDURAN                              19
ECEBLBALAO                              19
ECESMESMERALDAS                         19
ECGYEGUAYAQUIL                          19
ECGYQGUAYAQUIL                          19
ECMECMANTA                              19
ECPBOPUERTO BOLIVAR                     19
ECPUNPUNA                               19
ECPVOPORTO VIEJO                        19
ECSLRSAN LORENZO                        19
ECTEPTEPRE                              19
EEMUGMUUGA                              01
EEMUUPort: EEMUU                        ZZ
EEPLAPort: EEPLA                        ZZ
EEPLSPALDISKI LOUNASADAM                01
EETLLTALLINN                            01
EEUREKURESAAARE                         01
EGADAADABIYA                            04
EGAISAIN SUKHNA                         04
EGAKIABU KIR                            10
EGALYALEXANDRIA                         10
EGAQUAL QUSAYR                          04
EGASWASWAN                              10
EGCAIEL QAHIRA (= CAIRO)                10
EGDAMDAMIETTA                           10
EGEDKEL DEKHEILA                        10
EGIKUIDKU                               10
EGISMISMAILIA                           04
EGPIBPORT IBRAHIM                       04
EGPSAPort: EGPSA                        99
EGPSDPORT SAID                          10
EGPSEPT SAID EAST                       10
EGSOKSOKHNA PORT                        04
EGSUZSUEZ                               04
ERASAASSAB                              04
ERMSWMASSAWA                            04
ESACEARRECIFE DE LANZAROTE              00
ESAGPMALAGA                             00
ESAGUAGUILAS                            00
ESALCALICANTE                           00
ESALDALCUDIA                            00
ESALGALGECIRAS                          00
ESARIARGUINEGUIN                        00
ESAVSAVILES                             00
ESBCNBARCELONA                          00
ESBIOBILBAO                             00
ESBRXBURRIANA                           00
ESCADCADIZ                              00
ESCARCARTAGENA                          00
ESCASCASTELLON DE LA PLANA              00
ESCBSCALA SABINA                        00
ESCEUCEUTA                              00
ESDNADENIA                              00
ESEASSAN SEBASTIAN                      00
ESESCESCOMBRERAS                        00
ESFEREL FERROL                          00
ESFROFERROL                             00
ESFUEPTO. ROSARIO                       00
ESGANGANDIA                             00
ESGIJGIJON                              00
ESGRYGRAO                               00
ESHIEHIERRO                             00
ESHUVHUELVA                             00
ESIBZIBIZA                              00
ESJAVJAVEA                              00
ESLASPort: ESLAS                        99
ESLCGLA CORUNA                          00
ESLEIALMERIA                            00
ESLPALAS PALMAS, GRAN CANARIA           00
ESMAHMAHON                              00
ESMLNMELILLA                            00
ESMOTMOTRIL                             00
ESMPGMARIN, PONTEVEDRA                  00
ESPALPALAMOS                            00
ESPASPASAJES                            00
ESPEVPort: ESPEV                        ZZ
ESPMIPALMA DE MALLORCA                  00
ESPSMPUERTO DE SANTA MARIA              00
ESQIUCIUDADELA                          00
ESROSROSAS                              00
ESROTPort: ESROT                        ZZ
ESSAASAN ANTONIO                        00
ESSAGSAGUNTO                            00
ESSCRSAN CARLOS DE LA RAPITA            00
ESSCTSANTA CRUZ DE TENERIFE             00
ESSDRSANTANDER                          00
ESSFOSAN FERNANDO                       00
ESSNRSANTURCE                           00
ESSPCSANTA CRUZ DE LA PALMA             00
ESSPOPort: ESSPO                        ZZ
ESSSGSAN SEBASTIAN DE LA GOMERA         00
ESSVQSEVILLA                            00
ESTARTARRAGONA                          00
ESTCIPort: ESTCI                        99
ESTORTORREVIEJA                         00
ESTOTTORTOSA                            00
ESTRFPort: ESTRF                        ZZ
ESVGOVIGO                               00
ESVILVILLAGARCIA                        00
ESVITPort: ESVIT                        ZZ
ESVLCVALENCIA                           00
ESVLGVILANOVA Y LA GELTRU               00
ESZAZPort: ESZAZ                        00
ETMSWMASSAWA                            04
FIDEGDEGERBY                            01
FIESPESPOO (ESBO)                       01
FIGDBGODBY                              01
FIHELHELSINKI (HELSINGFORS)             01
FIHKOHANKO (HANGO)                      01
FIHMNFREDRIKSHAMN (HAMINA)              01
FIHOUHOUTSKAR                           01
FIIMAIMATRA                             01
FIKALKALLVIKRN                          01
FIKLAKLAMILA                            01
FIKOKKOKKOLA (KARLEBY)                  01
FIKTKKOTKA                              01
FIKUOKUOPIO                             01
FIKVOKUIVASTO                           01
FILAPLAPPOHJA (LAPPVIK)                 01
FILOVLOVIISA                            01
FILPPLAPPEENRANTA                       01
FIMLOMANTYLUOTO                         01
FIMTLMANTYLUOTO/PORI                    01
FIOLKOLKILUOTO                          01
FIOLUOULU                               01
FIOULOULU (ULEABORG)                    01
FIPORPORI (BJORNEBORG)                  01
FIPRSJACOBSTAD (PIETARSAARI)            01
FIRAURAUMA (RAUMO)                      01
FIRTRRAUTARUUKKI                        01
FISALSALO                               01
FITKUABO (TURKU)                        01
FITMPTAMPERE (TAMMERFORS)               01
FITOKTOLKKINEN (TOLKIS)/PORVOO          01
FITORTORNIO (TORNEA)                    01
FITURTURUN SAARISTO MUUT                01
FIUKIUUSIKAUPUNKI (NYSTAD)              01
FIVKKVARJAKKA                           01
FIVKOVALKO (VALKOM)                     01
FIVRKVARKAUS                            01
FJELLELLINGTON                          09
FJLTKLAUTOKA                            09
FJNAMNAMBOUWALU                         09
FJSUVSUVA                               09
FJVATVATIA                              09
FMTKKCHUUK (EX TRUK)                    09
FMYAPYAP                                09
FRABBABBEVILLE                          01
FRAGFAGEN                               01
FRAJAAJACCIO                            02
FRANTANTIBES                            02
FRAVNAVIGNON                            02
FRBAIBASSE-INDRE                        01
FRBASBASSENS                            01
FRBAYBAYONNE                            01
FRBBRBASSE TERRE                        17
FRBEEBERRE                              02
FRBESBREST                              01
FRBIABASTIA                             02
FRBODBORDEAUX                           01
FRBONBONIFACIO                          02
FRCEQCANNES                             02
FRCERCHERBOURG                          01
FRCFRCAEN                               01
FRCLYCALVI                              02
FRCOZCARONTE                            02
FRCQFCALAIS                             01
FRCSSCHALON-SUR-SAONE                   01
FRDKKDUNKERQUE                          01
FRDONDONGES                             01
FRETBETANG DE BERRE                     02
FRFDFFORT DE FRANCE                     17
FRFOSFOS-SUR-MER                        02
FRFSMPort: FRFSM                        99
FRGLOGONFREVILLE L'ORCHER               01
FRGVLGENNEVILLIERS                      01
FRHONHONFLEUR                           01
FRLAVLAVERA                             02
FRLCTLA CIOTAT                          02
FRLEHLE HAVRE                           01
FRLIBLIBOURNE                           01
FRLIOLYON                               02
FRLLSLONS LE SAUNIER                    02
FRLPELA PALLICE                         01
FRLPTLE PORT                            01
FRLRTL´ORIENT                           01
FRLSOLES SABLES D'OLONNE                01
FRLTRLE TREPORT                         01
FRLVELE VERDON                          01
FRMACMACON                              02
FRMPLMONTPELLIER                        02
FRMRSMARSEILLE                          02
FRMTXMONTOIR DE BRETAGNE                01
FRNCENICE                               02
FRNOUPORT-LA-NOUVELLE                   02
FRNTENANTES                             01
FRNVSNEVERS                             01
FRPARPARIS                              01
FRPDBPORT DE BOUC                       02
FRPJEPORT-JEROME                        01
FRPNOPLANCOET                           02
FRPOVPORT VENDRES                       02
FRPSLPORT ST LOUIS DU RHONE             02
FRPTPPOINTE A PITRE                     17
FRPVOPORTO VECCHIO                      02
FRRCOROCHEFORT                          01
FRRHEREIMS                              01
FRRIVRIVESALTES                         02
FRRONRONCQ                              01
FRRYNROYAN                              01
FRSETSETE                               02
FRSLMST LAURENT DU MARONI               01
FRSMLST MALO                            01
FRSRLSAINT RAPHAEL                      02
FRSTAST AVOLD                           01
FRSTPST TROPEZ                          02
FRTINPANTIN                             02
FRTLNTOULON                             02
FRUROROUEN                              01
FRVAFVALENCE                            02
FRVIHVILLEFRANCHE SUR-                  02
FRVLLVILLEFRANCHE-DE-ROUERGUE           02
FRVNEVANNES                             01
FRVSSVILLEFRANCHE SUR SAONE             02
FRYNELA SEYNE-SUR-MER                   02
GACLZCAP LOPEZ                          11
GAEKUEKUATA                             11
GAGAXGAMBA                              11
GALBVLIBREVILLE                         11
GALUCLUCINA                             11
GAOWEOWENDO                             11
GAPOGPORT GENTIL                        11
GBABDABERDEEN                           01
GBAVOAVONMOUTH                          01
GBAYRAYR                                01
GBBAWBALTIC WHARF/LONDON                01
GBBELBELFAST                            01
GBBFYPORT TALBOT-BRITON FERRY           01
GBBOSBOSTON                             01
GBBRFBRITON FERRY/PORT TALBOT           01
GBBRKBIRKENHEAD                         01
GBBRLBRISTOL                            01
GBBRPBRIDPORT/WEYMOUTH                  01
GBBRSBRISTOL                            01
GBBRWBRIDGWATER/WATCHET                 01
GBBSHBRIGHTON                           01
GBBSYBARNSLEY                           01
GBBWKBERWICK UPON TWEED                 01
GBCANCANVEY ISLAND                      01
GBCDFCARDIFF                            01
GBCHEMOSTYN                             01
GBCOYCORYTON                            01
GBCTFCASTLEFORD                         01
GBCTMCHATHAM                            01
GBCVTCOVENTRY                           01
GBDAGDAGENHAM                           01
GBDUNDUNDEE                             01
GBDVRDOVER                              01
GBDXYDERBY                              01
GBEAMEASTHAM                            01
GBELLELLESMERE PORT                     01
GBFALFALMOUTH                           01
GBFAWFAWLEY                             01
GBFLWFLIXBRIGH WHARF/SCUNTHORPE         01
GBFLXFLIXTON                            01
GBFOYFOWEY                              01
GBFXTFELIXSTOWE                         01
GBFYSFOYNES                             01
GBGLOGLOUCESTER                         01
GBGLWGLASGOW                            01
GBGOOGOOLE                              01
GBGRGGRANGEMOUTH                        01
GBGRKGREENOCK                           01
GBGRWGROVE WHARVES/SCUNTHORPE           01
GBGSYGRIMSBY                            01
GBGTNGARSTON/LIVERPOOL                  01
GBGUWGUNNESS WHARF/SCUNTHORPE           01
GBHDDHOWDENDYKE/GOOLE                   01
GBHDFHUDDERSFIELD                       01
GBHNUPort: GBHNU                        ZZ
GBHOPHOUND POINT                        01
GBHRWHARWICH                            01
GBHTPHARTLEPOOL                         01
GBHULHULL                               01
GBIMMIMMINGHAM                          01
GBINKINVERKEITHING                      01
GBIOMISLE OF MAN                        01
GBIPSIPSWICH                            01
GBIVGINVERGORDON/INVERNESS              01
GBJERJERSEY                             01
GBKLNKINGS LYNN                         01
GBLANLANCASTER/HEYSHAM                  01
GBLCNLINCOLN                            01
GBLCSLEICESTER                          01
GBLIVLIVERPOOL                          01
GBLONLONDON                             01
GBLYMLYMINGTON/SOUTHAMPTON              01
GBMIDMIDDLESBOROUGH                     01
GBMLFMILFORD HAVEN                      01
GBMNCMANCHESTER                         01
GBNCLNEWCASTLE UPON TYNE                01
GBNLNNELSON                             01
GBNPTNEWPORT                            01
GBNRWNORWICH/GREAT YARMOUTH             01
GBNRYNEWRY                              01
GBNTGNOTTINGHAM                         01
GBNWKNEWARK E                           01
GBODHOLDHAM                             01
GBPFTPURFLEET                           01
GBPLYPLYMOUTH                           01
GBPOOPOOLE                              01
GBPRUPORTBURY                           01
GBPTBPORT TALBOT                        01
GBPTHPORTISHEAD/BRISTOL                 01
GBRDNREADING                            01
GBRIDRIDHAM DOCK/ROCHESTER              01
GBROYROSYTH                             01
GBRUNRUNCORN                            01
GBSCPSCUNTHORPE                         01
GBSEASEAHAM/SUNDERLAND                  01
GBSEDSALT END                           01
GBSHESHEFFIELD                          01
GBSHOSHOREHAM                           01
GBSHSSHEERNESS/ROCHESTER                01
GBSOTSTOKE ON TRENT                     01
GBSOUSOUTHAMPTON                        01
GBSOWSTANLOW                            01
GBSUNSUNDERLAND                         01
GBSWASWANSEA                            01
GBTEETEESPORT                           01
GBTHPTHAMESPORT                         01
GBTILTILBURY/LONDON                     01
GBTNMTEIGNMOUTH                         01
GBTYNTYNE                               01
GBWAFPort: GBWAF                        ZZ
GBWATWATCHET                            01
GBWGNWIGAN                              01
GBWISWISBECH                            01
GBWPTNEWRY-WARRENPOINT                  01
GBYRKYORK                               01
GDGREGRENVILLE                          17
GDSTGSAINT GEORGE'S                     17
GEBUSBATUMI                             03
GEPTIPOTI                               03
GFCAYCAYENNE                            18
GFDDCDEGRAD DES CANNES                  18
GHACCACCRA                              11
GHADAADA                                11
GHCCTCAPE COAST                         11
GHSEKSEKONDI                            11
GHSHASHAMA                              11
GHTEMTEMA                               11
GHTKDTAKORADI                           11
GHWEAWINNEBA                            11
GIGIBGIBRALTAR                          01
GMBJLBANJUL                             11
GNBTYBENTY                              11
GNCKYCONAKRY                            11
GPBBRBASSE TERRE                        17
GPGUSGUSTAVIA                           17
GPPTPPOINTE A PITRE                     17
GQBSGBATA                               11
GQBULBUTUKU-LUBA                        11
GQLUBLUBA                               11
GQSSGMALABO                             11
GRACHAKHARNAI                           03
GRAGEAGIOS GEORGIOS                     03
GRAGTAGIO THEODOROI                     03
GRAIGAIGIALI AMORGOU                    03
GRANDANDROS                             03
GRANIAGHIOS NICOLAOS                    03
GRAPYASPROPYRGOS                        03
GRASSASPROPIRGOS                        03
GRASTASTAKOS                            03
GRATHATHINAI (ATHENS)                   03
GRCFUCORFU                              03
GRCLKCHALKIS                            03
GRCRGCORINTH                            03
GRDOSDELOS                              03
GREEUELEUSIS                            03
GRGPAPATRAS                             03
GRGRAAGIOS IOANNIS RENTIS               03
GRGYTGYTHION                            03
GRHERIRAKLION (HERAKLION)               03
GRHYDHYDRA (IDHRA)                      03
GRIGOIGOUMENITSA                        03
GRIOAIOANNINA                           03
GRITAITEA                               03
GRJMKMIKONOS                            03
GRKLMKALAMAKI                           03
GRKLXKALAMATA                           03
GRKVAKAVALA                             03
GRKZIKOZANI                             03
GRLAVLAVRION (LAURIUM)                  03
GRLRALARISA                             03
GRMLOMILOS                              03
GRNKVNEA KARVALI                        03
GRPIRPIRAEUS                            03
GRPLIPYLI                               03
GRPSAPSAKHNA                            03
GRPTLPORTO LAGOS                        03
GRPVKPREVEZA                            03
GRPYRPYRGOS                             03
GRRETRETHYMNON                          03
GRSKASKARAMANGA                         03
GRSKGTHESSALONIKI                       03
GRSKUSKYROS ISLAND                      03
GRSYSSTYLIS                             03
GRTHEPort: GRTHE                        99
GRTSITSINGELI                           03
GRVOLVOLOS                              03
GRVTHPORT VATHY                         03
GRYLIYALI ISLAND                        03
GTCHRCHAMPERICO                         17
GTLIVLIVINGSTON                         17
GTPBRPUERTO BARRIOS                     17
GTPRQPUERTO QUETZAL                     17
GTSNJSAN JOSE                           17
GTSTCSANTO TOMAS DE CASTILLA (M. GALVEZ)17
GTVINVILLA NUEVA                        17
GUAPRAPRA (AGANA)                       09
GUGUMGUAM                               09
GWBOLBOLAMA                             11
GWBXOBISSAU                             11
GWCACCACHEU                             11
GWOXBBISSAU                             11
GYGEOGEORGETOWN                         18
HKHKGHONG KONG                          08
HKKWNKOWLOON                            08
HNAMPAMAPALA                            17
HNLCELA CEIBA                           17
HNPCAPUERTO CASTILLA                    17
HNPCRPUERTO CORTES                      17
HNSAPSAN PEDRO SULA                     17
HNSLOSAN LORENZO                        17
HNTEATELA                               17
HNTGUTEGUCIGALPA                        17
HRBAKBAKAR                              03
HRDBVDUBROVNIK                          03
HRKORKORCULA                            03
HRPLEPLOCE (= KARDELJEVO)               03
HRPUYPULA                               03
HRRJKRIJEKA BAKAR                       03
HRSIBSIBENIK                            03
HRSPUSPLIT                              03
HRSUSSUSAK                              03
HRVRAVRANJIC                            03
HTACALES CAYES                          17
HTCAPCAP-HAITIEN                        17
HTPAPPORT AU PRINCE                     17
HUBUDBUDAPEST                           03
HUMOHMOHACS                             03
IDADBADANG BAY                          07
IDAMAAMAMAPARE, IJ                      07
IDARJARJUNA, JAVA                       07
IDBAKBATU KILAT                         07
IDBALBALONGAN TERMINAL                  07
IDBDJBANJARMASIN                        07
IDBEKBEKAPAI TERMINAL                   07
IDBGGBANGGAI                            07
IDBITBITUNG, SULAWESI                   07
IDBKSBENGKULU, SUMATRA                  07
IDBLWBELAWAN, SUMATRA                   07
IDBMTBIMA TERMINAL, JV                  07
IDBOABENOA, BALI                        07
IDBPNBALIKPAPAN, KALIMANTAN             07
IDBURBATU AMPAL                         07
IDBXTBONTHAN BAY, SULAWESI              07
IDDJADJANKAR                            07
IDDJBJAMBI, SUMATRA                     07
IDDUMDUMAI, SUMATRA                     07
IDGREGRESIK, JAVA                       07
IDJAKPort: IDJAK                        99
IDJKTJAKARTA-TANJUNG PRIOK, JAVA        07
IDKASKASIM, IJ                          07
IDKKAKUALA KAPUAS, KL                   07
IDKMAKUALA MANDAH, SUMATRA              07
IDKTJKUALATANJUNG                       07
IDLAHLABUHAN, JAVA                      07
IDLUWLUWUK                              07
IDMAKMAKASSAR                           07
IDMESMEDAN, SUMATRA                     07
IDMNTMANTANG, RIAU                      07
IDMRKMERAK, JAVA                        07
IDPAGPAGATAN, KALIMANTAN                07
IDPALPALU                               07
IDPASPASIR PANJANG                      07
IDPDGPADANG-TELUK BAJUR, SUMATRA        07
IDPJGPANJANG (LAMPUNG, SUMATRA)         07
IDPJMPANDJUNG MANI                      07
IDPKNPANGKALANBUUN                      07
IDPKRPANGKALAN BRANDAN, SUMATRA         07
IDPLMPALEMBANG, SUMATRA                 07
IDPNGPENUBA                             07
IDPNJPANJANG                            07
IDPNKPONTIANAK KALIMANTAN               07
IDPWGPERAWANG, SUMATRA                  07
IDSBGSABANG, SUMATRA                    07
IDSEBSEBANGAN BAY, KALIMANTAN           07
IDSEMPort: IDSEM                        99
IDSEQSUNGAI PAKNING, SUMATRA            07
IDSNPSUMENEP, MADURA                    ZZ
IDSPASELAT PANDJANG, SUMATRA            07
IDSRGSEMARANG, JAVA                     07
IDSRISAMARINDA, KALIMANTAN              07
IDSSOSUSU                               07
IDSUBSURABAYA, JAVA                     07
IDSUGSUNGAI GERONG, SUMATRA             07
IDSURPort: IDSUR                        99
IDTANTANJUNG UBAN, RIAU                 07
IDTBNTUBAN, JV                          07
IDTJBASAHAN (TANJUNG BALAI)             07
IDTJPTANJUNGPERAK                       07
IDTLITOLITOLI                           07
IDTNJTANJUNG PINANG, RIAU               07
IDTPPTANJUNG PRIOK                      07
IDUPGUJUNG PANDANG, SULAWESI            07
IDUTEJAKARTA UTC3                       07
IEALQALEXANDRA QUAY                     01
IEARDARDMORE                            01
IEAUGAUGHINISH ISLAND                   01
IEBTMBALTIMORE                          01
IEBTYPort: IEBTY                        99
IEDUBDUBLIN                             01
IEFENFENIT                              01
IEFOVFOYNES                             01
IEGWYGALWAY                             01
IELMKLIMERICK                           01
IENRSNEW ROSS                           01
IEORKCORK                               01
IERINRINGASKIDDY                        01
IETARTARBERT                            01
IEWATWATERFORD                          01
ILACRACRE                               03
ILAKLASHKELON                           03
ILASDPort: ILASD                        99
ILASHASHDOD                             03
ILHFAHAIFA                              03
ILRAHRAFAH                              03
ILTLVPort: ILTLV                        ZZ
INAGRAGRA                               06
INALFALLEPPEY                           06
INBDQVADODARA (BARODA)                  06
INBEYBEYPORE                            06
INBLRBANGALORE                          06
INBNDBANDDAR                            06
INBOMBOMBAY                             06
INCAMCAMBAY                             06
INCCUCALCUTTA                           06
INCOKCOCHIN                             06
INCOLCOLOCHEL                           06
INDAMDAMAN                              06
INENRENNORE                             06
INHALHALDIA                             06
INICDNEW DELHI                          06
INIXEMANGALORE (NEW MANGALORE)          06
INIXUAURANGABAD                         06
INIXYKANDLA                             06
INJAKJAKHAU                             06
INJBDJAFRABAD                           06
INJGAJAMNAGAR                           06
INJTPJAITAPUR                           06
INKBTKHAMBHAT                           06
INKKUJAIPUR-KANAKPURA                   06
INKRIKRISHNAPATAM                       06
INKRKKARIKAL                            06
INKRWKARWAR                             06
INMAAMADRAS                             06
INMAHMAHE                               06
INMGRMANGROL                            06
INMLIMAROLI                             06
INMRMMORMUGAO                           06
INMUNMUNDRA                             06
INMURMURAD                              06
INNANNANCOWRIE                          06
INNMLNEW MANGALORE (MANGALORE)          06
INNSANHAVA SHEVA                        06
INPANPANAJI, GOA                        06
INPAVPIPAVAV (ALBERT VICTOR)            06
INPBDPORBANDAR                          06
INPRTPARADIP                            06
INRAMRAMESHWARAM                        06
INSALSALAYA                             06
INSIKSIKA                               06
INSTVSURAT                              06
INTUTTUTICORIN (NEW TUTICORIN)          06
INVIGVIZAGAPATANAM                      06
INVIZVIZAG                              06
INVTZVISAKHAPATNAM                      06
IQBGWBAGHDAD                            05
IQBSRBASRA                              05
IQFAOFAO                                05
IQHILHILLAH                             05
IQMANMANDALI                            05
IQNASNAJAT                              05
IQOSMMOSUL                              05
IQSAMSAMARA                             05
IQUQRUMM QASR                           05
IRABDABADAN                             05
IRASAASALUYEH                           05
IRBKMBANDAR KHOMEINI                    05
IRBNDBANDAR ABBAS                       05
IRBSRBANDAR SHAHID REJAIE               05
IRBUZBUSHEHR                            05
IRIFNISFAHAN                            05
IRKASKASHAN                             05
IRKHOKHORRAMSHAHR                       05
IRTBZTABRIZ                             05
IRTHRTEHRAN                             05
IRZBRCHAH-BAHAR                         05
ISAKRAKRANES                            01
ISREKREYKJAVIK                          01
ISREYREYKJAVIK                          01
ITAGRAGRIGENTO                          02
ITAHOALGHERO                            02
ITALEALESSANDRIA                        02
ITAOIANCONA                             02
ITAUGAUGUSTA                            02
ITBDSBRINDISI                           02
ITBLQBOLOGNA                            02
ITBLTBARLETTA                           02
ITBRIBARI                               02
ITCAGCAGLIARI                           02
ITCGCCORIGLIANO CALABRO                 02
ITCHICHIOGGIA                           02
ITCTACATANIA                            02
ITCTRCASTELLAMMARE DEL GOLFO            02
ITCTWCROTONE                            02
ITCV Port: ITCV                         99
ITCVVCIVITAVECCHIA                      02
ITFALFALCONARA                          02
ITFOLFOLLONICA                          02
ITGAEGAETA                              02
ITGALGALLIPOLI                          02
ITGEAGELA                               02
ITGITGIOIA TAURO                        02
ITGOAGENOVA                             02
ITIMPIMPERIA                            02
ITLICLICATA                             02
ITLIVLIVORNO                            02
ITMAZMAZARA DEL VALLO                   02
ITMDCMARINA DI CARRARA                  02
ITMELMELILLI                            02
ITMILMILANO                             02
ITMLZMILAZZO                            02
ITMNFMONFALCONE                         02
ITMNPMONOPOLI                           02
ITMOLMOLFETTA                           02
ITMRAMARSALA                            02
ITMSNMESSINA                            02
ITNAPNAPOLI                             02
ITOLBOLBIA (TERRANOVA)                  02
ITPESPESARO                             02
ITPFEPORTOFERRAIO                       02
ITPFXSARROCH (=PORTO FOXI)              02
ITPGNPORTO NOGARO                       02
ITPIOPIOMBINO                           02
ITPMAPORTO MARGHERA                     02
ITPMOPALERMO                            02
ITPNDPONTEDERA                          02
ITPNGPORTO NOGARO                       02
ITPNLPANTELLERIA                        02
ITPOMPOMEZIA                            02
ITPOZPOZZUOLI                           02
ITPRIPRIOLO                             02
ITPRLPRIOLO GARGALLO                    02
ITPTFPORTOFINO                          02
ITPTOPORTO TORRES                       02
ITPVEPORTO VESME (PORTOSCUSO)           02
ITPZLPOZZALLO                           02
ITQOSORISTANO                           02
ITRANRAVENNA                            02
ITREGREGGIO CALABRIA                    02
ITROMROMA                               02
ITRROSORRENTO                           02
ITSALSALERNO                            02
ITSIRSIRACUSA                           02
ITSNPSAN PIETRO                         02
ITSPASANTA PANAGIA                      02
ITSPELA SPEZIA                          02
ITSRESAN REMO                           02
ITSVNSAVONA                             02
ITTARTARANTO                            02
ITTNITRANI                              02
ITTOATORRE ANNUNZIATA                   02
ITTPSTRAPANI                            02
ITTRSTRIESTE                            02
ITTRVTREVISO                            02
ITVADVADO/BOLOGNA                       02
ITVCEVENEZIA                            02
ITVDLVADO LIGURE                        02
ITVDOVADO/LUCCA                         02
ITVSOVASTO                              02
ITZINZINGONIA                           02
IT**3Port: IT**3                        99
JMKINKINGSTON                           17
JMMBJMONTEGO BAY                        17
JMSAWST ANNS BAY                        17
JOAMMAMMAN                              04
JOAQBAQABA FREE ZONE                    04
JOAQJAQABA (EL AKABA)                   04
JPABAABASHIRI, HOKKAIDO                 08
JPABOABOSHI, HYOGO                      08
JPAJXAJA, OKINAWA                       08
JPAKIAIKAKITA                           08
JPAKTAKITSU, HIROSHIMA                  08
JPAXTAKITA, AKITA                       08
JPCHBCHIBA, CHIBA                       08
JPFKMFUKUSHIMA, NAGASAKI                08
JPFKYFUKUYAMA, HIROSHIMA                08
JPGAMGAMAGORI, AICHI                    08
JPHHEHACHINOHE, AOMORI                  08
JPHHRHIGASHIHARIMA, HYOGO               08
JPHICHITACHINAKA                        08
JPHIJHIROSHIMA, HIROSHIMA               08
JPHIKHIKI, WAKAYAMA                     08
JPHISHIKOSHIMA, YAMAGUCHI               08
JPHKKHYAKKAN                            08
JPHKTHAKATA, FUKUOKA                    08
JPHRHHIROHATA, HYOGO                    08
JPHROHIRO, HIROSHIMA                    08
JPHSMHOSOJIMA, MIYAZAKI                 08
JPHTCHITACHI, IBARAGI                   08
JPIMBIMABARI, EHIME                     08
JPISIISHIKARI, HOKKAIDO                 08
JPISSISHIKARIWAN-SHINKO, HOKKAIDO       08
JPIWKIWAKUNI, YAMAGUCHI                 08
JPIYMIYOMISHIMA, EHIME                  08
JPJKTKOTOURA                            08
JPKARKARATSU, SAGA                      08
JPKCZKOCHI, KOCHI                       08
JPKIJNIIGATA, NIIGATA                   08
JPKKMKATAKAMI, OKAYAMA                  08
JPKMJKUMAMOTO, KUMAMOTO                 08
JPKNDKANDA, FUKUOKA                     08
JPKNZKANAZAWA, ISHIKAWA                 08
JPKOBKOZA                               08
JPKOIKOIKE/UWAJIMA                      08
JPKOSKOSE                               08
JPKSAKASAOKA, OKAYAMA                   08
JPKSCKASHIMA, SAGA                      08
JPKSMKASHIMA, IBARAGI                   08
JPKUHKUSHIRO, HOKKAIDO                  08
JPKWSKAWASAKI, KANAGAWA                 08
JPKZMKAZUME                             08
JPMAOMATSUO                             08
JPMIZMIZUSHIMA, OKAYAMA                 08
JPMKSMITSUKOSHIMA, HIROSHIMA            08
JPMOJMOJI, FUKUOKA                      08
JPMROMUROKITA                           08
JPMURMURORAN, HOKKAIDO                  08
JPMYJMATSUYAMA, EHIME                   08
JPNAANAGAURA, NAGASAKI                  08
JPNAGNAGAHAMA, SHIMANE                  08
JPNAHNAHA, OKINAWA                      08
JPNAKNAKAGUSUKU, OKINAWA                08
JPNANNAKANOSEKI                         08
JPNAONAOETSU, NIIGATA                   08
JPNATNAKATSU, OITA                      08
JPNDYNADAYAMA                           08
JPNEMNEMURO, HOKKAIDO                   08
JPNGONAGOYA, AICHI                      08
JPNGSNAGASAKI, NAGASAKI                 08
JPNGYPort: JPNGY                        ZZ
JPNKNNAKANOURA                          08
JPNKTNAKATA, HIROSHIMA                  08
JPNOMNOMIZAKI                           08
JPOITOITA, OITA                         08
JPOMZOMAEZAKI, SHIZUOKA                 08
JPONAONAHAMA, FUKUSHIMA                 08
JPOSAOSAKA, OSAKA                       08
JPOSIOHSHIMA, EHIME                     08
JPOSKOSAKI, MIYAGI                      08
JPOTKOTAKE, HIROSHIMA                   08
JPSAKSAKAI, OSAKA                       08
JPSBSSHIBUSHI, KAGOSHIMA                08
JPSDJSENDAI, MIYAGI                     08
JPSDSSENDAI-SHINKO, MIYAGI              08
JPSENSENDAI, KAGOSHIMA                  08
JPSHGSHINAGAWA, TOKYO                   08
JPSINSHIINOKI                           08
JPSKTSAKATA, YAMAGATA                   08
JPSMASOUMA, FUKUSHIMA                   08
JPSMNSAKAIMINATO, TOTTORI               08
JPSMZSHIMIZU, SHIZUOKA                  08
JPTAKTAKAMATSU, KAGAWA                  08
JPTBTTOBATA, FUKUOKA                    08
JPTHSTOYOHASHI, AICHI                   08
JPTKMTAKUMA, KAGAWA                     08
JPTKSTOKUSHIMA, TOKUSHIMA               08
JPTKYTOKUYAMA, YAMAGUCHI                08
JPTMJTAKAMI                             08
JPTMKTOMAKOMAI, HOKKAIDO                08
JPTMNTAMANOURA                          08
JPTMTTAMATSU, OKAYAMA                   08
JPTOGTOKI (TOGI), ISHIKAWA              08
JPTOJTOGA                               08
JPTOKTOKACHI, HOKKAIDO                  08
JPTOSTOYAMASHINKO, TOYAMA               08
JPTOXTOSHIMA/TOKYO                      08
JPTOYTOYAMA, TOYAMA                     08
JPTYNTSUIYAMA                           08
JPTYOTOKYO, TOKYO                       08
JPTYPTSUYOSHI                           08
JPUBJUBE, YAMAGUCHI                     08
JPUKAUSUKA                              08
JPUKBKOBE, HYOGO                        08
JPUKJUKEJIMA                            08
JPYATYATSUSHIRO, KUMAMOTO               08
JPYKKYOKKAICHI, MIE                     08
JPYOCYOICHIGAURA                        08
JPYOKYOKOHAMA, KANAGAWA                 08
JPYOSYOKOSUKA, KANAGAWA                 08
JPYSMYOSHIMA                            08
JPYUKYUKI                               08
KEKILKILINDINI                          12
KEKISKISUMU                             12
KELAULAMU                               12
KEMBAMOMBASA                            12
KEMYDMALINDI                            12
KHCHECHEKO                              07
KHKKOKAS KONG                           07
KHKOSKOMPONGSOM                         07
KHPNHPHNOMPENH                          07
KHSIHSIHANOUKVILLE                      07
KMAJNANJOUAN                            12
KMFOUFOUMBOUNI                          12
KMMUTMUTSAMUDU                          12
KMYVAMORONI                             12
KNBASBASSETERRE, ST KITTS               17
KPGENGENSAN                             08
KPHGMHUNGNAM                            08
KPNAMNAMPO                              08
KPSONSONGJIN                            08
KRCHACHEJU                              08
KRDASPort: KRDAS                        99
KRICHINCHEON                            08
KRINCINCHEUN                            08
KRINHINCHON                             08
KRKANGWANGYANG                          08
KRKPOPOHANG                             08
KRKSNKUNSAN                             08
KRKUVGUNSAN                             08
KRKWAKWANGYANG                          08
KRKWJGWANGJU                            08
KRMASMASAN                              08
KRMOKMOKPO                              08
KROKPOKPO/GEOJE                         08
KRONSONSAN                              08
KRPTKPYEONGTAEK                         08
KRPUSBUSAN                              08
KRSHGSINHANG/POHANG                     08
KRTAEDAEGU                              08
KRTANTAEAN-GUN                          08
KRTSNDAESAN                             08
KRUSNULSAN                              08
KRWNDWANDO-GUN                          08
KWJAHJAHRAN                             05
KWJBDJEBEL DHANA                        05
KWKWIKUWAIT                             05
KWMEAMENA AL AHMADI                     05
KWMIBMINA ABD ALLAH                     05
KWMISMINA SAUD                          05
KWSAASHUAIBA                            05
KWSWKSHUWAIKH                           05
KYGECGEORGETOWN, GRAND CAYMAN           17
LBBEYBEIRUT                             03
LBCHKCHEKKA                             03
LBKYETRIPOLI                            03
LBSAYSAYDA                              03
LBTIOTRIPOLI                            03
LCCASCASTRIES                           17
LCCDSCUL DE SAC                         17
LCSLUPORT CASTRIES                      17
LCVIFVIEUX FORT                         17
LKBTCBATTICOLOA                         06
LKCMBCOLOMBO                            06
LKGALGALLE                              06
LKMANMANNAR                             06
LRCMTCAPE MOUNT                         11
LRCPACAPE PALMAS                        11
LRFIMFIMIBO                             11
LRGREGREENVILLE                         11
LRHARHARPER                             11
LRMARMARSHALL                           11
LRMLWMONROVIA                           11
LRROXROBERTSPORT                        11
LRSABSARIOE BAY                         11
LRSNISINOE                              11
LRTRTTRADE TOWN                         11
LRUCNBUCHANAN                           11
LTKLJKLAIPEDA                           01
LULUXLUXEMBOURG                         01
LVLPXLIEPAYA                            01
LVRIXRIGA                               01
LVVNTVENTSPILS                          01
LYABAAL BAYDA                           10
LYABKABU KAMMASH                        10
LYBENBENGHAZI                           10
LYKHOALKHUMS                            10
LYLMQMARSA BREGA                        10
LYMBRMARSA BREGHA                       10
LYMRAMISURATA                           10
LYRLARAS LANUF                          10
LYTIPTRIPOLI                            10
LYTOBTOBRUK                             10
LYZAWZAWIA TERMINAL (AZZAWIYA)          10
MAAGAAGADIR                             10
MACASCASABLANCA                         10
MAELJELJADIDA                           10
MAEUNLAAYOUNE (EL AAIUN)                10
MAJFLJORF LASFAR                        10
MALARLARACHE                            10
MAMOHMOHAMMEDIA                         10
MANDRNADOR                              10
MANNAKENITRA (EX PORT LYAUTEY)          10
MAPTMTANGER MED                         10
MARAKMARRAKACH                          10
MARBARABAT                              10
MASFISAFI                               10
MATNGTANGIER                            10
MATTUTETUAN                             10
MAVILDAKHLA                             10
MCMCMMONTE-CARLO                        02
MCMONMONACO                             02
MDGIUGIURGIULESTI                       03
MEBARBAR                                03
MEKOTKOTOR                              03
MGADKANDROKA                            12
MGBIKBRICKAVILLE                        12
MGBPYBESALAMPY                          12
MGDIEDIEGO SUAREZ (ANTSIRENANA)         12
MGDWBSOALALA                            12
MGHLVHELL-VILLE                         12
MGIVAAMBANJA                            12
MGMJNMAJUNGA (MAHAJANGA)                12
MGMOBMANOMBO                            12
MGMOQMORONDAVA                          12
MGMXTMAINTIRANO                         12
MGNOSNOSY-BE                            12
MGPSLPORT SAINT LOUIS                   12
MGTLETULEAR (TOLIARA)                   12
MGTMMTAMATAVE (TOAMASINA)               12
MGTOATOAMASINA                          12
MGVATVATOMANDRY                         12
MGVVBMAHANORO                           12
MHTARTAROA                              09
MHZZZPort: MHZZZ                        99
MLBKOBAMAKO                             11
MMAKYAKYAB                              07
MMPEGPEGU                               07
MMRGNYANGON                             07
MMXYEYE                                 07
MOFMMPort: MOFMM                        ZZ
MOMACMACAU                              08
MOMFMMACAU                              08
MPSPNSAIPAN                             09
MQFDFFORT DE FRANCE                     17
MRNDBNOUADHIBOU (FORMERLY PORT ETIENNE) 11
MRNKCNOUAKCHOTT                         11
MRPCEPOINT CENTRAL                      11
MSPLYPLYMOUTH                           17
MTCKWCIRKEWWA                           03
MTDISMALTA FREEPORT DISTRIPARK          03
MTMARMARSAXLOKK                         03
MTMLAMALTA (VALETTA)                    03
MUPLUPORT LOUIS                         12
MVKELKELAI                              06
MVMLEMALE                               06
MXACAACAPULCO, GRO                      15
MXATMALTAMIRA                           15
MXCOACOATZACOALCOS, VER                 15
MXCPECAMPECHE-LERWA                     15
MXCZMCOZUMEL, ROO                       15
MXESEENSENADA, BCN                      15
MXGYMGUAYMAS, SON                       15
MXLZCLAZARO CARDENAS, MIC               16
MXMIDMERIDA, YUC                        15
MXMTTMINATITLAN                         16
MXMZTMAZATLAN, SIN                      15
MXNAUNAUTLA                             15
MXPGOPROGRESO, YUC                      15
MXPMSPUERTO MORELOS                     15
MXPMXPUERTO MEXICO, COA                 15
MXPVRPUERTO VALLARTA, GRO               16
MXRSTROSARITO TERMINAL                  16
MXSCXSALINA CRUZ                        16
MXTAMTAMPICO, TAM                       15
MXTIJTIJUANA, BCN                       16
MXTUXTUXPAN, JER                        15
MXVERVERACRUZ                           15
MXZCACADEREYTA JIMENEZ                  15
MXZLOMANZANILLO, COL                    16
MYBAGBAGAN DATOK                        07
MYBBABATU BATU, SABAH                   07
MYBKIKOTA KINABALU, SABAH               07
MYBKPBAKAPIT                            07
MYBLIBATU LINGTAN, SARAWAK              07
MYBNTBENUT, JOHOR                       07
MYBTNBINTANGOR                          07
MYBTUBINTULU, SARAWAK                   07
MYBWHBAGAN LUAR (BUTTERWORTH)           07
MYDRODARO, SARAWAK                      07
MYJHBJOHORE BHARU                       07
MYKABKABONG, SARAWAK                    07
MYKBAKUALA BARAM                        07
MYKBSKUALA BESAR                        07
MYKCHKUCHING, SARAWAK                   07
MYKIMKIMANIS, SABAH                     07
MYKKHKUALA KEDAH                        07
MYKSLKUALA SELANGOR                     07
MYKTIKOTA TINGGI                        07
MYKUAKUANTAN (TANJONG GELANG)           07
MYKUNKUNAK, SABAH                       07
MYLBULABUAN, SABAH                      07
MYLDULAHAD DATU, SABAH                  07
MYLGKLANGKAWI                           07
MYLUMLUMUT                              07
MYLUNLUNDU, SARAWAK                     07
MYLUTLUTONG, SARAWAK                    07
MYMERMERSING                            07
MYMYYMIRI, SARAWAK                      07
MYPAGPort: MYPAG                        99
MYPANPANCHANG                           07
MYPASPASIR GOGOK                        07
MYPDIPORT DICKSON                       07
MYPENPENANG (GEORGETOWN)                07
MYPGGPENGGARANG/TANJ.PENGILEH           07
MYPGUPASIR GUDANG, JOHOR (JOHOR PORT)   07
MYPKEPort: MYPKE                        99
MYPKGPORT KELANG (SWETTENHAM)           07
MYPKKPENGKALAN KUBOR                    07
MYSBWSIBU, SARAWAK                      07
MYSDKSANDAKAN, SABAH                    07
MYSELSELALANG, SARAWAK                  07
MYSHASHAH ALAM                          07
MYSILSILAY                              07
MYSIRSIRAN                              07
MYSPTSIPITANG, SABAH                    07
MYSRESUNGAI RENGIT                      07
MYTKPTANJONG KUPANG                     07
MYTPPTANJONG PELEPAS                    07
MYTWUTAWAU, SABAH                       07
MYWESWESTON, SABAH                      07
MZANOANGOCHE                            12
MZBELBELA VISTA                         12
MZBEWBEIRA                              12
MZMATMATOLA                             12
MZMNCNACALA                             12
MZMPMMAPUTO                             12
MZMZQMOCAMBIQUE                         12
MZPBEPORTO BELO                         12
MZPOLPEMBA                              12
MZUELQUELIMANE                          12
NALUDLUDERITZ                           11
NAWVBWALVIS BAY                         11
NCBUGBAIE UGUE                          09
NCDUSDUCOS                              09
NCKOUKOUAOUA                            09
NCNOUNOUMEA                             09
NCPORPORO                               09
NGABOABONNEMA                           11
NGADOADO                                11
NGANTANTAN TERMINAL                     11
NGAPPAPAPA                              11
NGBONBONNY                              11
NGBRABRASS                              11
NGBURBURUTU                             11
NGCBQCALABAR                            11
NGERTEHRA TERMINAL                      11
NGGRPGREEK PORT                         11
NGLOSLAGOS                              11
NGONNONNE                               11
NGPHCPORT HARCOURT                      11
NGTINTINCAN/LAGOS                       11
NGWARWARRI                              11
NIBEFBLUEFIELDS/EL BLUFF                17
NICIOCORINTO                            17
NIPSNPUERTO SANDINO                     17
NIPUZPUERTO CABEZAS                     17
NISJSSAN JUAN DEL SUR                   17
NLAAMAALSMEER                           01
NLAKLAKERSLOOT                          01
NLAMSAMSTERDAM                          01
NLBOTBOTLEK                             01
NLDORDORDRECHT                          01
NLDZLDELFZIJL                           01
NLEUREUROPOORT                          01
NLIJMIJMUIDEN                           01
NLMOEMOERDIJK                           01
NLMSLMAASSLUIS                          01
NLMSTMAASTRICHT                         01
NLRTMROTTERDAM                          01
NLSCESCHEVENINGEN (S-GRAVENHAGE)        01
NLSCISCHIEDAM                           01
NLTNZTERNEUZEN                          01
NLVLAVLAARDINGEN                        01
NLVLIVLISSINGEN                         01
NOAANARDAL                              01
NOAESALESUND                            01
NOAGOAGOTNES                            01
NOANDANDALSNES                          01
NOBGOBERGEN                             01
NOBINBINDAL                             01
NOBLLBALLANGEN                          01
NOBOOBODO                               01
NODRKDROBAK                             01
NODRMDRAMMEN                            01
NOFDEFORDE-DYRANA                       01
NOFFDFLEKKEFJORD                        01
NOFRKFREDRIKSTAD                        01
NOFROFLORO                              01
NOFRSFORUS                              01
NOHALHALDEN                             01
NOHAUHAUGESUND                          01
NOHFTHAMMERFEST                         01
NOHORHORTEN                             01
NOHVGHONNINGSVAG                        01
NOKOPKOPERVIK                           01
NOKRSKRISTIANSAND                       01
NOLARLARVIK                             01
NOLAVLAVANGEN                           01
NOMQNMO I RANA                          01
NOMSSMOSS                               01
NONODNORDDAL                            01
NOODDODDA                               01
NOOSLOSLO                               01
NOPORPORSGRUNN                          01
NOSADSANDEFJORD                         01
NOSASSANDNES                            01
NOSTASTATHELLE                          01
NOSTVSTAVERN                            01
NOSVGSTAVANGER                          01
NOSVJSVOLVAER                           01
NOTONTONSBERG                           01
NOTOSTROMSO                             01
NOTRDTRONDHEIM                          01
NOTVETVEDESTRAND                        01
NOULSULSTEINVIK                         01
NOVAOVARDO                              01
NZAKAAKARON                             09
NZAKLAUCKLAND                           09
NZASGASHBURTON                          09
NZBHEBLENHEIM                           09
NZBLUBLUFF HARBOUR                      09
NZCGECAMBRIDGE                          09
NZCHCLYTTELTON/CHRISTCHURCH             09
NZDUDDUNEDIN                            09
NZHLZHAMILTON                           09
NZIVCINVERCARGILL                       09
NZLYTLYTTELTON                          09
NZMMUMOUNT NAUNGANUI                    09
NZNPENAPIER                             09
NZNPLNEW PLYMOUTH                       09
NZNSNNELSON                             09
NZPEOPENROSE                            09
NZPOEPORT CHALMERS                      09
NZTIUTIMARU                             09
NZTRGTAURANGA                           09
NZWLGWELLINGTON                         09
OMFAHFAHAL                              05
OMMCTMUSCAT                             05
OMMNQMINA' QABUS                        05
OMMUTMUTHRA                             05
OMOPQPORT QABAS                         05
OMQALQALHAT                             05
OMRAYRAYSUT                             05
OMSLLSALALAH                            05
OMSOHSOHAR                              05
OMSULPORT SULTAN                        05
PAAGDAGUADULCE                          17
PAAMLPUERTO ARMUELLES                   17
PABLBBALBOA                             17
PACHACHARCO AZUL                        17
PACRBCHRISTOBAL OUTPORTS                17
PACTBCRISTOBAL                          17
PACTDCHITRE                             17
PAELEEL REAL                            17
PAMITMANZANILLO                         17
PAMNPLAS MINAS                          17
PAONXCOLON                              17
PAPAIPARAISO                            17
PAPAMPUERTO ALMIRANTE                   17
PAPAYPAYARDI                            17
PAPLPLA PALMA                           17
PAPTYPANAMA CITY                        17
PAVACVACAMONTE                          17
PEANCANCON                              19
PECHMCHIMBOTE                           19
PECLLCALLAO                             19
PEILQILO                                19
PELIMLIMA                               19
PELOOLOS ORGANOS                        19
PEPAIPAITA                              19
PEPIOPISCO                              19
PEPMTPIMENTEL                           19
PEPSCPISCO-GEN SAN MARTIN               19
PESJASAN JUAN                           19
PESVYSALAVERRY                          19
PETRUTRUJILLO                           19
PFBOBBORA BORA                          09
PFPPTPAPEETE                            09
PFVAIVAITAPE                            09
PGABWABAU                               09
PGAKIAKINUM                             09
PGGURALOTAU                             09
PGKIMKIMBE                              09
PGLAELAE, MOROBE                        09
PGPOMPORT MORESBY                       09
PGRABRABAUL                             09
PGROROROBAY                             09
PHABUABULOG/APARRI                      08
PHAHEAHERON/OZAMIS                      08
PHALAALASANG/SIAIN                      08
PHALEALERAN/OZAMIS                      08
PHBABBABATO/DADIANGAS                   08
PHBCOBACON/LEGASPI                      08
PHBGCBAGAC                              08
PHBIYBIYAWA/DAVAO                       08
PHBLTBALINTANG/PUERTO PRINCESA          08
PHBLUBALUMO/ZAMBOANGA                   08
PHBOGBOGO/CAGAYAN DE ORO                08
PHBOSBOSTON/DAVAO                       08
PHBRTBARTON/PUERTO PRINCESA             08
PHBTGBATANGAS, LUZON                    08
PHBUGBUGO                               08
PHCBYCALBAYONG/CATBALOGAN               08
PHCEBCEBU                               08
PHCGYCAGAYAN DE ORO, MINDANAO           08
PHDGTDUMAGUETE                          08
PHDVODAVAO, MINDANAO                    08
PHGESGENERAL SANTOS/DADIANGAS           08
PHGINGINGOOG/MASAO                      08
PHIGNILIGAN, MINDANAO                   08
PHJNZJIMENEZ/OZAMIS                     08
PHKIWKIWALAN/ILIGAN                     08
PHLGPLEGASPI, DAVAO                     08
PHLPALIPA                               08
PHLPZLA PAZ/ILOILO                      08
PHMANPort: PHMAN                        99
PHMASMASAO                              08
PHMCOMACO/DAVAO                         08
PHMLLMALALAG/DAVAO                      08
PHMNLMANILA                             08
PHMNNMANILA NORTH HARBOUR               08
PHMNSMANILA SOUTH HARBOUR               08
PHMNYMANAY/MATI                         08
PHMXIMATI, MINDANAO                     08
PHPASPASAY, LUZON                       08
PHPPLPAMPLONA/APARRI                    08
PHQUEQUESON/SIAIN                       08
PHRXSROXAS/PUERTO PRINCESA              08
PHSASSASA/DAVAO                         08
PHSFSSUBIC BAY                          08
PHSINSIAIN, LUZON                       08
PHSKUSULTAN KUDARAT/DADIANGAS           08
PHTAYTAYTAY/PUERTO PRINCESA             08
PHTLSTOLOSA/TACLOBAN                    08
PHVNVVILLANUEVA                         08
PHZAMZAMBOANGA, MINDANAO                08
PKBQMMUHAMMAD BIN QASIM/KARACHI         06
PKGWDGWADAR                             06
PKJIWJIWANI                             06
PKKBUKETI BUNDER                        06
PKKCTKARACHI CONTAINER TERMINAL         06
PKKHIKARACHI                            06
PKPSIPASNI                              06
PLDARDARLOWO                            01
PLGDNGDANSK                             01
PLGDYGDYNIA                             01
PLKOLKOLOBRZEG                          01
PLSWISWINOUJSCIE                        01
PLSZZSZCZECIN                           01
PRAREARECIBO                            17
PRMAZMAYAGUEZ                           17
PRPSEPONCE                              17
PRSJUSAN JUAN                           17
PTAVEAVEIRO                             01
PTCACCACEM                              01
PTFAOFARO                               01
PTFNCFUNCHAL, MADEIRA                   01
PTLEILEIXOES                            01
PTLISLISBOA                             01
PTLOSLAGOS                              01
PTMATMATOSINHOS                         01
PTOPOPORTO                              01
PTPDLPONTA DELGADA, AZ                  01
PTPDSPONTE DE SOR                       01
PTPENPENICHE                            01
PTPRMPORTIMAO                           01
PTSETSETUBAL                            01
PTSIESINES                              01
PTSINSINES                              01
PTVDCVIANA DO CASTELO                   01
PYASUASUNCION                           18
PYCNPCONCEPCION                         18
PYENOENCARNACION                        18
PYPFXPUERTO FENIX                       18
PYSANSAN ANTONIO                        18
PYTERTERPORT (SAN ANTONIO)              18
PYVLLVILLETA                            18
QADOHDOHA                               05
QAHNAHANNA                              05
QAMESMESAIEED                           05
QARLFRAS LAFFAN                         05
QAUMSUMMSAID                            05
RELPTLE PORT                            12
REPDGPOINTE DES GALETS                  12
REREUREUNION                            12
RERUNPOINTE DES GALETS                  06
ROAGIAGIGEA                             03
ROBABBASARABI                           03
ROBRABRAILA                             03
ROCNDCONSTANTA                          03
ROCSZPort: ROCSZ                        99
ROGALGALATI                             03
ROMIDMIDIA                              03
ROSULSULINA (PORT ET ZONE FRANCHE)      03
RSAPTAPATIN                             03
RSBZDBEZDAM                             03
RUARHARKHANGELSK                        01
RUARMARMAN (MAGADAN)                    08
RUAZOAZOV                               03
RUBKHPort: RUBKH                        ZZ
RUBLTBALTIYSK                           01
RUCIHPort: RUCIH                        ZZ
RUDYRANADYR                             08
RUGOJNIZHNIY NOVGOROD (EX GORKIY)       03
RUKANKANDALAKSHA                        01
RUKDTKRONSHTADT                         01
RUKGDKALININGRAD                        01
RUKHVKHABAROVSK                         08
RUKLDKILDIN                             01
RUKORKORSAKOV                           08
RUKRRKRASNODAR                          03
RUKUFSAMARA (EX KUIBYSHEV)              03
RULEDST PETERSBURG (EX LENINGRAD)       01
RUMAGMAGADANSKY, PORT                   08
RUMMKMURMANSK                           01
RUMOWMOSCOW                             01
RUMVOMOSKALVO                           08
RUNEVNEVELSK                            03
RUNJKNAKHODKA                           08
RUNVSNOVOROSSIYSK                       03
RUPRIPRIMORSK (KOIVISTO)                01
RUROVROSTOV                             03
RURTWSARATOV                            03
RUSEGSEGEZHA                            01
RUSHASHAKHTERSK                         01
RUTAGTAGANROG                           03
RUTTITOLYATTI                           03
RUTUATUAPSE                             03
RUVOGVOLGOGRAD                          03
RUVVOVLADIVOSTOK                        01
RUVYGVYBORG                             01
RUVYPVOSTOCHNIY, PORT                   01
RUVZBVOZROZHDENIYA, BUKHTA              03
RUYEYYEYSK                              03
RUZHDMARIUPOL (EX ZHDANOV)              03
SAAAKABU AL KHOOSH                      04
SAAHAAL HADA                            05
SAALKAL KHOBAR                          04
SADASDAS ISLAND                         04
SADHADHAHRAN                            04
SADHUDHUBA                              04
SADMMSADMM DAMMAM (KING ABDUI AZIZ PORT)05
SADMNDAMMAN                             04
SAGIZGIZAN                              04
SAHDYAL HUDAYDAH (HODEIDA)              04
SAJEDJEDDAH                             04
SAJUBJUBAIL                             05
SAMAKMAKKAH                             04
SAQURQURAYYAH                           05
SARABRABIGH                             04
SARTARAS TANURA                         05
SASUHSALBOUKH                           04
SAYBIYANBU INDUSTRIAL CITY              04
SAYNBYANBU                              04
SBHIRHONIARA, GUADALCANAL ISLAND        09
SCMAWMAHE                               12
SCPOVPORT VICTORIA                      12
SDPZUPORT SUDAN                         04
SDSWASWAKIN                             04
SEAARAR                                 01
SEAHUAHUS                               01
SEALAALA                                01
SEALFALFREDSHEM                         01
SEAMAAMAL                               01
SEARBARBRA                              01
SEBROBROFJORDEN                         01
SEFAGFALKENBERG                         01
SEGOTGOTHENBURG                         01
SEGVXGAVLE                              01
SEHANHARGSHAMN                          01
SEHELHELSINGBORG                        01
SEHLDHOLMSUND                           01
SEHNDHARNOSAND                          01
SEJARJARFALLA                           01
SEJKGJONKOPING                          01
SEJOHJOHANNEDAL                         01
SEKLRKALMAR                             01
SEKSDKARLSTAD                           01
SELLALULEA                              01
SELYSLYSEKIL                            01
SEMMAMALMO                              01
SENOLNOL (PORTS), O                     01
SENRKNORRKOPING                         01
SEOERORNSKOLDSVIK                       01
SEOSKOSKARSHAMN                         01
SEOXEOXELOSUND                          01
SEPITPITEA                              01
SERNBRONNEBY                            01
SESDLSUNDSVALL                          01
SESOESODERTALJE                         01
SESORSORAKER                            01
SESTOSTOCKHOLM                          01
SESUGSUNDBYBERG                         01
SETOAPort: SETOA                        ZZ
SETUNTUNADAL                            01
SEUDDUDDEVALLA                          01
SEVAGVARBERG                            01
SEVSTVASTERAS                           01
SEWALWALLHAMN                           01
SGAYCPULAN AYER CHAWAN                  07
SGJURJURONG                             07
SGKEPKEPPEL WHARVES                     07
SGPUBPULAU BUKOM                        07
SGSCTSINGAPORE CONTAINER TERMINAL       07
SGSEBPULAU SEBAROK                      07
SGSEMSEMBAWANG PORT                     07
SGSGPPort: SGSGP                        99
SGSINSINGAPORE                          07
SGTAYTELOK AYER BASIN                   07
SIIZOIZOLA                              03
SIKOPKOPER                              03
SIPIRPIRAN                              03
SKBABBRATISLAVA PORT                    03
SKKNPKOMARNO PORT                       03
SLBTEBONTHE                             11
SLFNAFREETOWN                           11
SLNITNITTI                              11
SLPEPPEPEL                              11
SLSBOSHERBRO                            11
SNDKRDAKAR                              11
SNFOUFOUNDIOUGNE                        11
SNMBAM'BAO TERMINAL                     11
SNZIGZIGUINCHOR                         11
SOBBOBERBERA                            12
SOMERMERCA                              12
SOMGQMOGADISHU                          12
SRABNALBINA                             18
SRPBMPARAMARIBO                         18
STPCPPRINCIPE                           11
STSAASANTO ANTONIO                      11
STTMSSAO TOME ISLAND                    11
SUNVSNOVOROSSIYSK                       03
SUODEPort: SUODE                        99
SUODSODESSA                             03
SVAQJACAJUTLA                           17
SVBANBANI                               17
SVCJOCABO JOJO                          17
SVHAIHAINA                              17
SVLLDLA LIBERTAD                        17
SVLUNLA UNION                           17
SVMANMANZANILLO                         17
SVPVAPUERTO VIEJO DE AZUA               17
SVSABSABANA                             17
SVSALSAN SALVADOR                       17
SVSCISANTO TOMAS DE CASTILLA            17
SVSDOSANTO DOMINGO                      17
SYBANBANIYAS                            03
SYDAMDAMASCUS                           03
SYLTKLATAKIA                            03
SYTTSTARTOUS                            03
TCPLSPROVIDENCIALES                     17
TGANEANECHO                             11
TGKPEKPEME                              11
TGLFWLOME                               11
THBGPBANGPAKONG                         07
THBKKBANGKOK                            07
THBMTBANGKOK MODERN TERMINALS/BANGKOK   07
THBNLBANLAEM                            07
THBTPBAN TAJUA PA                       07
THCHACHANTABUN                          07
THHKTPHUKET                             07
THKLYKLONG-YAI                          07
THKSIKOH SICHANG                        07
THKTYKHLONG TOEI                        07
THLCBPort: THLCB                        99
THLCHLAEM CHABANG                       07
THLKRPort: THLKR                        99
THMATMAB TAPUD                          07
THPKNPAKNAM                             07
THSATSATTAHIP                           07
THSGZSONGKHLA                           07
THSRISRIRACHA                           07
THTSTTRANG                              07
THUCTUNITHAI CONTAINER TERMINAL         07
THUNNRANONG                             07
TMTMZTERMEZ                             03
TNASHASHTART TERMINAL                   10
TNBIZBIZERTE                            10
TNGAEGABES                              10
TNLGNLA GOULETTE NORD (HALQUELOUED)     10
TNLSKLA SKHIRRA                         10
TNRADRADES                              10
TNRDSRADES/TUNIS                        10
TNSFASFAX                               10
TNSUSSOUSSE                             10
TNTUNTUNIS                              10
TR   Port: TR                           99
TRADAADANA                              03
TRALIALIAGA                             03
TRAMBAMBARLI                            03
TRANAANAMUR, ICEL                       03
TRAYTANTALYA                            03
TRBDMBANDIRMA, BALIKESIR                03
TRBUYBUYUKCUKUR, BURSA                  03
TRCAMCAMALTI, ISMIR                     03
TRCESCESME, IZMIR                       03
TRCUBCUBUKLU, ISTANBUL                  03
TRDARDARICA                             03
TRDIKDIKILI, IZMIR                      03
TRDILDILISKELESI                        03
TRDRCDERINCE, KOCAELI                   03
TREDIEDIRNE                             03
TREREEREGLI, ZONGULDAK                  03
TREVYPort: TREVY                        99
TREYPEVYAP                              03
TRFETFETHIYE, MUGLA                     03
TRGEBGEBZE                              03
TRGEMGEMLIK, BURSA                      03
TRGULGULLUK, MUGLA                      03
TRHARHARAMIDERE, ISTANBUL               03
TRHAYHAYDARPASA, ISTANBUL               03
TRISKISKENDERUN, HATAY                  03
TRISTISTANBUL                           03
TRIZMIZMIR (SMYRNA)                     03
TRIZTIZMIT, KOCAELI                     03
TRKARKARTAL, ISTANBUL                   03
TRKMXKUMPORT                            03
TRKUSKUSADASI, AYDIN                    03
TRLMALIMAS                              03
TRMERMERSIN, ICEL                       03
TRMPTMARPORT                            03
TRMRAMARMARA ADASI, BALIKESIR           03
TRMUDMUDANYA, BURSA                     03
TRNEMNEMRUT BAY                         03
TRPENPENDIK                             03
TRSSXSAMSUN                             03
TRTASTASUCU, ICEL                       03
TRTEKTEKIRDAG                           03
TRTURTURAN, IZMIR                       03
TRTUZPort: TRTUZ                        ZZ
TRTZXTRABZON                            03
TRYARYARIMCA, KOCAELI                   03
TRZONZONGULDAK                          03
TTCHACHAGUARAMAS                        17
TTLABLA BREA (BRIGHTON)                 17
TTPOSPORT OF SPAIN                      17
TTPTFPOINT FORTIN                       17
TTPTSPOINT LISAS                        17
TWAPGAN PING                            08
TWHUNHUALIEN                            08
TWKELKEELUNG (CHILUNG)                  08
TWKHHKAOHSIUNG (TAKAO)                  08
TWMALMAI-LIAI                           08
TWSUOSUAO                               08
TWTNNTAINAN                             08
TWTPETAIPEI                             08
TWTTTTAITUNG                            08
TWTXGTAICHUNG                           08
TWTYNTAYOUAN                            08
TZDARDAR ES SALAAM                      12
TZKIMKILWA MASOKO                       12
TZLDILINDI                              12
TZMWZMWANZA                             12
TZPANPANGANI                            12
TZSAMSAMANGA                            12
TZTGTTANGA                              12
TZTKQKIGOMA                             12
TZZNZZANZIBAR                           12
UABGDBELGOROD-DNESTROVSKIY              03
UAERDBERDYANSK                          03
UAFEOFEODOSIYA                          03
UAIEVKIEV                               03
UAILKILYICHEVSK                         03
UAIZMIZMAIL                             03
UAKEHKERCH                              03
UAKHEKHERSON                            03
UAMPWMARIUPOL (EX ZHDANOV)              03
UANIKNIKOLAYEV                          03
UAODSODESSA                             03
UARNIRENI                               03
UASHASHAKHTERSK                         03
UASVPSEVASTOPOL                         03
UAYUZYUZHNYY                            03
UGJINJINJA                              12
UMAWKWAKE ISLAND                        09
US   Port: US                           99
USAAFAPALACHICOLA, FL                   15
USAAYKENMORE AIR HARBOR                 ZZ
USABCPT HADLOCK,WA                      16
USABYALBANY, NY                         13
USACJSOUTH BEND                         16
USACUPort: USACU                        99
USALBALBURG, VT                         13
USALCALCAN, AK                          16
USANCANCHORAGE, AK                      16
USANDANDRADE, CA                        16
USANPANNAPOLIS, MD                      13
USANYPort: USANY                        99
USARBANN ARBOR, MI                      14
USASHASHTABULA, OH                      14
USASTASTORIA, OR                        16
USATWAPPLETON, WI                       14
USBALBALTIMORE, MD                      13
USBAYBAYONNE, NJ                        13
USBCBVANCOUVER, WN                      16
USBCLPort: USBCL                        ZZ
USBDRBRIDGEPORT, CO (?)                 13
USBDSBISCOE, NC                         13
USBLABLAINE, WN                         16
USBLIBELLINGHAM, WN                     16
USBMTPORT ARTHUR, TX                    15
USBNANASHVILLE, TN                      15
USBNCBENICIA, CA                        16
USBOSBOSTON, MA                         13
USBOYBROOKLYN/NEW YORK, NY              13
USBPTBEAUMONT, TX                       15
USBROBROWNSVILLE, TX                    15
USBRRBREWSTER, OH                       16
USBTRBATON ROUGE, LA                    15
USBTVBURLINGTON, VT                     13
USBUFBUFFALO, NY                        14
USCCTPort: USCCT                        ZZ
USCDECAMDEN, NJ                         13
USCDYCONNEAUT                           14
USCGEPort: USCGE                        ZZ
USCHAPort: USCHA                        99
USCHICHICAGO, IL                        14
USCHSCHARLESTON, SC                     13
USCHTCHESTER, PA                        14
USCIDCEDAR RAPIDS, IA                   14
USCLECLEVELAND, OH                      14
USCLQCHALMETTE                          15
USCLTPort: USCLT                        99
USCMMCOLUMBUS, NM                       14
USCNVCONVENT                            15
USCOVCOLUMBIA, WN                       16
USCPTCARPINTERIA, CA                    16
USCRICRISFIELD, MD                      ZZ
USCRPCORPUS CHRISTI, TX                 15
USCRTCARTERET, NJ                       13
USCRWCHARLESTON, WV                     14
USCSFCARTERET                           13
USCVGCINCINNATI, OH                     14
USDALDALLAS-FORT WORTH, TX              15
USDAVDAVENPORT, CA                      16
USDBQPort: USDBQ                        ZZ
USDECDECATUR, IL                        14
USDETDETROIT, MI                        14
USDFWDALLAS-FORT WORTH REG APT          15
USDLHDULUTH, MN                         14
USDOVDOUGLAS, AZ                        13
USDSMDES MOINES, IA                     15
USDURDURHAM, NC                         14
USDUTDUTCH HARBOR, AK                   16
USDVNPort: USDVN                        ZZ
USDVVDAVISVILLE, RI                     13
USEDLPort: USEDL                        ZZ
USEDMEDMONDS, WN                        16
USEGPEAGLE PASS, TX                     15
USEKIELKHART, IN                        14
USELKELKHART, IN                        14
USELZWELLSVILLE                         13
USERIERIE, PA                           14
USESFALEXANDRIA, VA                     13
USEVVPort: USEVV                        ZZ
USEWBNEW BEDFORD, MA                    13
USEWRNEWARK, NJ                         13
USEYWKEY WEST, FL                       15
USFABFABENS, TX                         15
USFEBFERNANDINA BEACH, FL               13
USFLLFORT LAUDERDALE                    17
USFPOFREEPORT, TX                       15
USFPRFORT PIERCE, FL                    13
USFROFRONTIER, WN                       16
USFRPPort: USFRP                        99
USFWAFORT WAYNE, IN                     14
USFWOFORT WORTH, TX (CF. DALLAS)        15
USGGEGEORGETOWN, SC                     13
USGHNGRAND HAVEN, MI                    14
USGLHGREENVILLE, MS                     15
USGLSGALVESTON, TX                      15
USGPTGULFPORT, MS                       15
USGRBGREEN BAY, WI                      14
USGRRGRAND RAPIDS, MI                   14
USGRYGRAMERCY, LA                       15
USGYYGARY, IN                           14
USHAHHAHNVILLE, LA                      15
USHBKPort: USHBK                        ZZ
USHIDHIDALGO, TX                        15
USHNLHONOLULU, HA                       16
USHOUHOUSTON, TX                        15
USHPYBAYTOWN, HOUSTON, TX               15
USHVNNEW HAVEN, CT                      13
USILGWILMINGTON, DE                     13
USILMWILMINGTON, NC                     13
USJAXJACKSONVILLE, FL                   13
USJECJERSEY CITY, NJ                    13
USJMCSAUSALITO, CA                      16
USJNUJUNEAU, AK                         16
USJVLPort: USJVL                        ZZ
USKASKASITNA BAY, AK                    16
USKCKKANSAS CITY, KS                    16
USKLZKALAMAZOO, MI                      14
USKTNKETCHIKAN, AK                      16
USLASPort: USLAS                        99
USLAXLOS ANGELES, CA                    16
USLCHLAKE CHARLES, LA                   15
USLDMPort: USLDM                        ZZ
USLGBLONG BEACH, CA                     16
USLGVLONGVIEW, CA                       16
USLGZLOGAN AIRPORT, MA                  13
USLUILOUISVILLE, KY                     13
USLWMPort: USLWM                        ZZ
USLXAPort: USLXA                        99
USLYNLYNDEN, WA                         16
USMAIMAIDA, ND                          13
USMCRMANCHESTER, WA                     16
USMEMMEMPHIS, TN                        14
USMESMINNEAPOLIS, MN                    14
USMIAMIAMI, FL                          13
USMKCKANSAS CITY, MO                    16
USMKEMILWAUKEE, WI                      14
USMKGMUSKEGON, MI                       14
USMOBMOBILE, AL                         15
USMRNMARINETTE, WI                      14
USMSPPort: USMSP                        99
USMSYNEW ORLEANS INTERNATIONAL APT      15
USMTKMETLAKATLA, AK                     16
USMTMPort: USMTM                        ZZ
USMTPPort: USMTP                        99
USMVIMELLVILLE, RI                      ZZ
USMZZMARION, IN                         13
USNASPort: USNAS                        99
USNECNECHE, ND                          ZZ
USNENNEWPORT NEWS/NORFOLK, VA           13
USNEWDESTREHAN (NEW ORLEANS), LA        15
USNFKPort: USNFK                        99
USNGZALAMEDA, CA                        16
USNPONEWPORT, OR                        16
USNPTNEWPORT, RI                        13
USNTDPORT HUENEME, CA                   16
USNYCNEW YORK, NY                       13
USNYKPort: USNYK                        99
USOAKOAKLAND, CA                        16
USOGSOGDENSBURG, NY                     14
USOKCOKLAHOMA CITY, OK                  13
USOLMOLYMPIA, WN                        16
USOLSNOGALES                            16
USOMAPort: USOMA                        ZZ
USORFNORFOLK, VA                        13
USORGORANGE, TX                         15
USORHWORCESTER, MA                      13
USPAHPort: USPAH                        ZZ
USPATPATERSON, NJ                       13
USPAYPERTH AMBOY, NJ                    13
USPBGPITTSBURG, CA                      13
USPBIWEST PALM BEACH, FL                13
USPBRPITSBURG, OH                       14
USPCAPORT CANAVERAL, FL                 13
USPCRPOINT COMFORT                      15
USPCTPOINT CONFORT, TX                  15
USPCVPORT CANAVERAL                     13
USPDXPORTLAND, OR                       16
USPEAPEARL HARBOUR, HONOLULU, HA        16
USPEFPORT EVERGLADES, FL                13
USPFNPANAMA CITY, FL                    15
USPGLPASCAGOULA, MS                     15
USPHFCHESAPEAKE/HAMPTON ROADS, VA       13
USPHLPHILADELPHIA, PA                   13
USPICPITTSBURG, CA/SAN JOAQUIN RIVER    16
USPIEST PETERSBURG, FL                  15
USPISPORT ISABEL/BROWNSVILL, TX         15
USPITPITTSBURGH, PA                     14
USPLLPORT ALLEN, LA                     15
USPLPPLEASANT PRAIRIE, WI               14
USPNSPENSACOLA, FL                      15
USPOBPORT BOLIVAR, TX                   15
USPSDPASADENA, CA                       15
USPSLPORT SAN LUIS, CA                  16
USPSMPORTSMOUTH, VA                     13
USPTLPT. ARMSTRONG                      16
USPTMPORTSMOUTH                         13
USPVCPROVINCETOWN, MA                   13
USPVDPROVIDENCE, RI                     13
USPWMPORTLAND, ME                       13
USPYMPLYMOUTH, MA                       ZZ
USQUIQUINCY/ST. ALBANS, MA              13
USRACRACINE, WI                         14
USRCHRICHMOND, CA                       16
USRCYROGER CIRY, MI                     14
USRICRICHMOND, VA                       13
USRIVREIDSVILLE, NC                     13
USRKDROCKLAND, ME                       13
USRNORENO, NV                           ZZ
USROCROCHESTER, NY                      14
USRSFRESERVE                            13
USSABSABINE, TX                         15
USSACSACRAMENTO, CA                     16
USSANSAN DIEGO, CA                      16
USSATSAN ANTONIO, TX                    15
USSAVSAVANNAH, GA                       13
USSBASANTA BARBARA                      16
USSBKPort: USSBK                        99
USSCKSTOCKTON, CA                       16
USSEASEATTLE, WN                        16
USSFNWOONSOCKET                         15
USSFOSAN FRANCISCO, CA                  16
USSFYSPRINGFIELD, MA                    13
USSIDPort: USSID                        99
USSJCSAN JOSE, CA                       16
USSMOSAN MATEO, CA                      16
USSNYSIDNEY, OH                         14
USSPGPort: USSPG                        99
USSPRSPRINGFIELD, MA                    13
USSRPSEARSPORT, ME                      13
USSRTSPARROWS POINT                     ZZ
USSRUSANTA CRUZ                         16
USSSIBRUNSWICK, GA                      13
USSTGST GEORGES ISLAND, AK              16
USSTLST LOUIS, MO                       16
USSTPST PAUL, MN                        14
USSTZPort: USSTZ                        ZZ
USSUWSUPERIOR, WI                       14
USSUXPort: USSUX                        ZZ
USTEOTHEODORE, AL                       15
USTIWTACOMA, WN                         16
USTOLTOLEDO, OH                         14
USTPATAMPA, FL                          15
USTULPort: USTUL                        ZZ
USTXTTEXAS CITY, TX                     15
USUFGCHESAPEAKE                         13
USUXNPort: USUXN                        99
USVANPort: USVAN                        ZZ
USVBNVAN BUREN, ME                      13
USVKSVICKSBURG                          15
USVLOVALLEJO, CA                        ZZ
USWASPort: USWAS                        99
USWODPort: USWOD                        99
USWOMWILMINGTON                         13
USWRDWEST REDDING, CT                   ZZ
USWRNWARREN                             13
USWTNWILMINGTON, CA                     16
USWWOWESTWEGO, LA                       15
USXNAPort: USXNA                        ZZ
USYNGWARREN, OH                         14
USYONYONKERS, NY                        13
UYCARCARMELO                            18
UYCYRCOLONIA                            18
UYFZBFRAY BENTOS                        18
UYMVDMONTEVIDEO                         18
UYNVPNUEVA PALMIRA                      18
VCKTNKINGSTOWN, ST VINCENT              17
VCSVDST VINCENT-ARNOS VALE              17
VCUNICLIFTON, UNION ISLAND              17
VEAMYAMUAY                              18
VEARAARAYA                              18
VEBAVBACHAQUERO/MARACAIBO L             18
VECARCARIPITO                           18
VECBLCIUDAD BOLIVAR                     18
VECUMCUMANA                             18
VEEGUEL GUAMACHE                        18
VEELPEL PALITO                          18
VEETVEL TABLAZO/MARACAIBO L             18
VEGUBGUARANAO BAY                       18
VEGUTGUANTA/PUERTO DE LA CRUZ           18
VELAGLA GUAIRA/CARACAS                  18
VELSPLAS PIEDRAS                        18
VEMARMARACAIBO                          18
VEMTVMATANZAS                           18
VEPBLPUERTO CABELLO                     18
VEPCAPUNTA CAMACHO                      18
VEPCNPUNTA CARDON                       18
VEPCZPUERTO LA CRUZ                     18
VEPFIPUNTO FIJO                         18
VEPLAPALUA                              18
VEPMVPALMAREJO DE MARA/MARACAIBO L.     18
VEPPZPUERTO PAEZ                        18
VEPSUPUERTO SUCRE                       18
VESFXSAN FELIX                          18
VETURTURIAMO                            18
VGRADROAD TOWN, TORTOLA                 17
VGTOVTORTOLA                            17
VICHACHARLOTTE AMELIE                   17
VICTDCHRISTIANSTED, ST. CROIX           17
VISTTST THOMAS                          17
VNBENBENTHUY                            07
VNBNGBEN NGHE                           07
VNCLICAT LAI                            07
VNCLNCAI LAN                            07
VNCMTCAI MEP INTERNATIONAL TERMINAL     07
VNCPHCAM PHA                            07
VNDADDA NANG                            07
VNDOHDONG HOI                           07
VNHAAHOAI AN                            07
VNHANHANOI                              07
VNHATHA TINH                            07
VNHCMPort: VNHCM                        99
VNHNHHOAI NHON                          07
VNHPGPort: VNHPG                        99
VNHPHHAIPHONG                           07
VNHUIHUE                                07
VNIPHPHUOC LONG ICD                     07
VNNHANHATRANG                           07
VNPHGPHUOC LONG                         07
VNPHLPHUOE LE                           07
VNQUNPort: VNQUN                        99
VNSGNHO CHI MINH CITY                   07
VNTBBTUY HOA                            07
VNTCGTAN CANG                           07
VNUIHQUI NHON                           07
VNVCACAN THO                            07
VNVICHO CHI MINH, VICT                  07
VNVIHQUINHON                            07
VNVUTVUNG TAU                           07
VNXNGQUANG NGAI                         07
VUPSAPORT SANDWICH                      09
WFMAUMata-Utu                           09
WSAPWAPIA                               09
YDPRMPERIM                              04
YEADEADEN                               04
YEHODHODEIDAH                           04
YEMKXMUKALLA                            04
YEPRMPERIM I.                           04
YESYESA DAH                             04
YTDZADZAOUDZI                           12
YTLONLONGONI                            12
YTMAMMAMOUDZOU                          12
YUBARBAR                                03
YUBEGBELGRADE                           03
ZAAOBALGOA BAY                          12
ZACPTCAPETOWN                           12
ZADURDURBAN                             12
ZAELSEAST LONDON                        12
ZAJTPJET PARK                           12
ZAMZYMOSSEL BAY                         12
ZANOLPORT NOLLOTH                       12
ZAPITPOINT                              12
ZAPLZPORT ELIZABETH                     12
ZARCBRICHARDS BAY                       12
ZASDBSALDANHA BAY                       12
ZAZBACOEGA                              12
ZRBOABOMA                               11
ZRMATMATADI                             11
ZZZZZDESCONOCIDO                        ZZ
