ADAndorra                                 043Andorra                                  D_MIRROR  00000000
AEEmiratos Arabes                         647Emiratos Arabes                          D_MIRROR  00000000
AFAfganistán                              660Afganistán                               D_MIRROR  00000000
AGAntigua y Barbuda (Castellà)            459Antigua y Barbuda (Castellà)             D_MIRROR  00000000
AIAnguila                                 446Anguila                                  D_MIRROR  00000000
ALAlbania                                 070Albania                                  D_MIRROR  00000000
AMArmenia                                 077Armenia                                  D_MIRROR  00000000
ANAntillas Neerlandesas                   478Antillas Neerlandesas                    D_MIRROR  00000000
AOAngola                                  330Angola                                   D_MIRROR  00000000
AQAntartica                               891Antartica                                D_MIRROR  00000000
ARArgentina                               528Argentina                                D_MIRROR  00000000
ASSamoa Americana                         830Samoa Americana                          D_MIRROR  00000000
ATAustria                                 038Austria                                 ED_MIRROR  00000000
AUAustralia                               800Australia                                D_MIRROR  00000000
AWAruba                                   474Aruba                                    D_MIRROR  00000000
AXALAND ISLANDS (JF)                      032ALAND ISLANDS (JF)                      ED_MIRROR  00000000
AZAzerbaiyan                              078Azerbaiyan                               D_MIRROR  00000000
BABosnia-Herzegovina                      093Bosnia-Herzegovina                       D_MIRROR  00000000
BBBarbados                                469Barbados                                 D_MIRROR  00000000
BDBangladesh                              666Bangladesh                               D_MIRROR  00000000
BEBélgica                                 017Bélgica                                 ED_MIRROR  00000000
BFBurkina Faso                            236Burkina Faso                             D_MIRROR  00000000
BGBulgaria                                068Bulgaria                                ED_MIRROR  00000000
BHBahrein                                 640Bahrein                                  D_MIRROR  00000000
BIBurundi                                 328Burundi                                  D_MIRROR  00000000
BJBenin                                   284Benin                                    D_MIRROR  00000000
BMBermuda                                 413Bermuda                                  D_MIRROR  00000000
BNBrunei                                  703Brunei                                   D_MIRROR  00000000
BOBolivia                                 516Bolivia                                  D_MIRROR  00000000
BRBrasil                                  508Brasil                                   D_MIRROR  00000000
BSBahamas                                 453Bahamas                                  D_MIRROR  00000000
BTBhutan                                  675Bhutan                                   D_MIRROR  00000000
BUBURMA (BIRMANIA)                        676BURMA (BIRMANIA)                         PRADASC   19990212
BVBouvet Island                           892Bouvet Island                            D_MIRROR  00000000
BWBotswana                                391Botswana                                 D_MIRROR  00000000
BYBielorrusia                             073Bielorrusia                              D_MIRROR  00000000
BZBelice                                  421Belice                                   D_MIRROR  00000000
CACanadá                                  404Canadá                                   D_MIRROR  00000000
CCCocos (Keeling) Islands                 833Cocos (Keeling) Islands                  D_MIRROR  00000000
CDR.D.Congo (ex Zaire)                    322R.D.Congo (ex Zaire)                     D_MIRROR  00000000
CFRepublica Centroafricana                306Republica Centroafricana                 D_MIRROR  00000000
CGCongo                                   318Congo                                    D_MIRROR  00000000
CHSuiza                                   039Suiza                                   FD_MIRROR  00000000
CICosta Marfil (d'Ivory)                  272Costa Marfil (d'Ivory)                   D_MIRROR  00000000
CKCook Islands                            837Cook Islands                             D_MIRROR  00000000
CLChile                                   512Chile                                    D_MIRROR  00000000
CMCamerún                                 302Camerún                                  D_MIRROR  00000000
CNChina                                   720China                                    D_MIRROR  00000000
COColombia                                480Colombia                                 D_MIRROR  00000000
CRCosta Rica                              436Costa Rica                               D_MIRROR  00000000
CSSERBIA AND MONTENEGRO                   094SERBIA Y MONTENEGRO                      BAGOTJ    20090722
CUCuba                                    448Cuba                                     D_MIRROR  00000000
CVCabo Verde                              247Cabo Verde                               D_MIRROR  00000000
CWCuraçao                                    Curaçao                                  BAGOTJ    00000000
CXChristmas Island                        834Christmas Island                         D_MIRROR  00000000
CYChipre                                  600Chipre                                  ED_MIRROR  00000000
CZRepública Checa                         061República Checa                         ED_MIRROR  00000000
DDALEMANIA (R.D.)                         004ALEMANIA (R.D.)                         EVILAJOSANA19951214
DEAlemania                                004Alemania                                ED_MIRROR  00000000
DJDjibouti                                338Djibouti                                 D_MIRROR  00000000
DKDinamarca                               008Dinamarca                               ED_MIRROR  00000000
DMDominica                                460Dominica                                 D_MIRROR  00000000
DORepública Dominicana                    456República Dominicana                     D_MIRROR  00000000
DZArgelia                                 208Argelia                                  D_MIRROR  00000000
ECEcuador                                 500Ecuador                                  D_MIRROR  00000000
EEEstonia                                 053Estonia                                 ED_MIRROR  00000000
EGEgipto                                  220Egipto                                   D_MIRROR  00000000
EHWestern Sahara                             Western Sahara                           D_MIRROR  00000000
EOESTONIA                                 053ESTONIA                                  VILAJOSANA19951122
EQEQUATORIAL GUINEA                       310GUINEA ECUATORIAL                        VILAJOES  19990713
EREritrea                                 336Eritrea                                  D_MIRROR  00000000
ESEspaña                                  011España                                  ED_MIRROR  00000000
ETEtiopia                                 334Etiopia                                  D_MIRROR  00000000
FIFinlandia                               032Finlandia                               ED_MIRROR  00000000
FJFiyi                                    815Fiyi                                     D_MIRROR  00000000
FKFalkland Islands (Malvinas)             529Falkland Islands (Malvinas)              D_MIRROR  00000000
FMMICRONESIA, FEDERATED STATES OF         823MICRONESIA, FEDERATED STATES OF          D_MIRROR  00000000
FOFaroe Islands                           041Faroe Islands                            D_MIRROR  00000000
FRFrancia                                 001Francia                                 ED_MIRROR  00000000
GAGabón                                   314Gabón                                    D_MIRROR  00000000
GBReino Unido                             006Reino Unido                             ED_MIRROR  00000000
GDGranada                                 473Granada                                  D_MIRROR  00000000
GEGeorgia                                 076Georgia                                  D_MIRROR  00000000
GFGuyana Francesa                         001Guyana Francesa                          D_MIRROR  00000000
GGGuernsey                                   Guernsey                                 D_MIRROR  00000000
GHGhana                                   276Ghana                                    D_MIRROR  00000000
GIGibraltar                               044Gibraltar                                D_MIRROR  00000000
GLGreenland                               406Greenland                                D_MIRROR  00000000
GMGambia                                  252Gambia                                   D_MIRROR  00000000
GNGuinea                                  260Guinea                                   D_MIRROR  00000000
GPGuadalupe                               001Guadalupe                                D_MIRROR  00000000
GQGuinea Ecuatorial                       310Guinea Ecuatorial                        D_MIRROR  00000000
GRGrecia                                  009Grecia                                  ED_MIRROR  00000000
GSSOUTH GEORGIA AND THE SOUTH SANDWICH ISL893SOUTH GEORGIA AND THE SOUTH SANDWICH ISL D_MIRROR  00000000
GTGuatemala                               416Guatemala                                D_MIRROR  00000000
GUGuam                                    831Guam                                     D_MIRROR  00000000
GWGuinea Bissau                           257Guinea Bissau                            D_MIRROR  00000000
GYGuyana                                  488Guyana                                   D_MIRROR  00000000
HKHong Kong                               740Hong Kong                                D_MIRROR  00000000
HMHEARD ISLAND AND MCDONALD ISLANDS       835HEARD ISLAND AND MCDONALD ISLANDS        D_MIRROR  00000000
HNHonduras                                424Honduras                                 D_MIRROR  00000000
HRCroacia                                 092Croacia                                  D_MIRROR  00000000
HTHaití                                   452Haití                                    D_MIRROR  00000000
HUHungria                                 064Hungria                                 ED_MIRROR  00000000
IDIndonesia                               700Indonesia                                D_MIRROR  00000000
IEIrlanda                                 007Irlanda                                 ED_MIRROR  00000000
ILIsrael                                  624Israel                                   D_MIRROR  00000000
IMIsla de Man                             006Isla de Man                              CORTESA   00000000
INIndia                                   664India                                    D_MIRROR  00000000
IOBritish Indian Ocean Territory          357British Indian Ocean Territory           D_MIRROR  00000000
IQIrak                                    612Irak                                     D_MIRROR  00000000
IRIran                                    616Iran                                     D_MIRROR  00000000
ISIslandia                                024Islandia                                FD_MIRROR  00000000
ITItalia                                  005Italia                                  ED_MIRROR  00000000
JEJersey                                     Jersey                                   D_MIRROR  00000000
JMJamaica                                 464Jamaica                                  D_MIRROR  00000000
JOJordania                                628Jordania                                 D_MIRROR  00000000
JPJapón                                   732Japón                                    D_MIRROR  00000000
KEKenia                                   346Kenia                                    D_MIRROR  00000000
KGKirguizistan                            083Kirguizistan                             D_MIRROR  00000000
KHCamboya (Kampuchea)                     696Camboya (Kampuchea)                      D_MIRROR  00000000
KIKiribati                                812Kiribati                                 D_MIRROR  00000000
KMComoras                                 375Comoras                                  D_MIRROR  00000000
KNSan Cristobal y Nieves                  449San Cristobal y Nieves                   D_MIRROR  00000000
KPCorea del Norte                         724Corea del Norte                          D_MIRROR  00000000
KRCorea del Sur                           728Corea del Sur                            D_MIRROR  00000000
KWKuwait                                  636Kuwait                                   D_MIRROR  00000000
KYIslas Caimán                            463Islas Caimán                             D_MIRROR  00000000
KZKazajistan                              079Kazajistan                               D_MIRROR  00000000
LALaos                                    684Laos                                     D_MIRROR  00000000
LBLíbano                                  604Líbano                                   D_MIRROR  00000000
LCSanta Lucía                             465Santa Lucía                              D_MIRROR  00000000
LILiechtenstein                           037Liechtenstein                            D_MIRROR  00000000
LKSri Lanka (Ceilán)                      669Sri Lanka (Ceilán)                       D_MIRROR  00000000
LRLiberia                                 268Liberia                                  D_MIRROR  00000000
LSLesotho                                 395Lesotho                                  D_MIRROR  00000000
LTLituania                                055Lituania                                ED_MIRROR  00000000
LULuxemburgo                              018Luxemburgo                              ED_MIRROR  00000000
LVLetonia                                 054Letonia                                 ED_MIRROR  00000000
LYLibia                                   216Libia                                    D_MIRROR  00000000
MAMarruecos                               204Marruecos                                D_MIRROR  00000000
MCMónaco                                  001Mónaco                                   D_MIRROR  00000000
MDMoldavia                                074Moldavia                                 D_MIRROR  00000000
MEMontenegro                              094Montenegro                               D_MIRROR  00000000
MGMadagascar                              370Madagascar                               D_MIRROR  00000000
MHIslas Marshall                          824Islas Marshall                           D_MIRROR  00000000
MKMacedonia                               096Macedonia                                D_MIRROR  00000000
MLMali                                    232Mali                                     D_MIRROR  00000000
MMMyanmar (Birmania)                      676Myanmar (Birmania)                       D_MIRROR  00000000
MNMongolia                                716Mongolia                                 D_MIRROR  00000000
MOMacau                                   743Macau                                    D_MIRROR  00000000
MPNorthern Mariana Islands                820Northern Mariana Islands                 D_MIRROR  00000000
MQMartiníca                               001Martiníca                                D_MIRROR  00000000
MRMauritania                              228Mauritania                               D_MIRROR  00000000
MSMontserrat                              470Montserrat                               D_MIRROR  00000000
MTMalta                                   046Malta                                   ED_MIRROR  00000000
MUMauricio                                373Mauricio                                 D_MIRROR  00000000
MVMaldivas                                667Maldivas                                 D_MIRROR  00000000
MWMalawi                                  386Malawi                                   D_MIRROR  00000000
MXMéxico                                  412México                                   D_MIRROR  00000000
MYMalasia                                 701Malasia                                  D_MIRROR  00000000
MZMozambique                              366Mozambique                               D_MIRROR  00000000
NANamibia                                 389Namibia                                  D_MIRROR  00000000
NCNueva Caledonia                         809Nueva Caledonia                          D_MIRROR  00000000
NENiger                                   240Niger                                    D_MIRROR  00000000
NFNorfolk Island                          836Norfolk Island                           D_MIRROR  00000000
NGNigeria                                 288Nigeria                                  D_MIRROR  00000000
NINicaragua                               432Nicaragua                                D_MIRROR  00000000
NLPaíses Bajos                            003Países Bajos                            ED_MIRROR  00000000
NONoruega                                 028Noruega                                 FD_MIRROR  00000000
NPNepal                                   672Nepal                                    D_MIRROR  00000000
NRNauru                                   803Nauru                                    D_MIRROR  00000000
NUNiue                                    838Niue                                     D_MIRROR  00000000
NZNueva Zelanda                           804Nueva Zelanda                            D_MIRROR  00000000
OMOmán                                    649Omán                                     D_MIRROR  00000000
PAPanamá                                  442Panamá                                   D_MIRROR  00000000
PCSEE FM MH MP PW                         999VER FM MH MP PW                          VILAJOSANA19951215
PEPerú                                    504Perú                                     D_MIRROR  00000000
PFPolinesia Francesa                      822Polinesia Francesa                       D_MIRROR  00000000
PGPapúa/Nueva Guinea                      801Papúa/Nueva Guinea                       D_MIRROR  00000000
PHFilipinas                               708Filipinas                                D_MIRROR  00000000
PKPakistán                                662Pakistán                                 D_MIRROR  00000000
PLPolonia                                 060Polonia                                 ED_MIRROR  00000000
PMSAINT PIERRE AND MIQUELON               408SAINT PIERRE AND MIQUELON                D_MIRROR  00000000
PNPitcairn                                813Pitcairn                                 D_MIRROR  00000000
PRPuerto Rico                             400Puerto Rico                              D_MIRROR  00000000
PSPALESTINIAN TERRITORY, OCCUPIED         625PALESTINIAN TERRITORY, OCCUPIED          D_MIRROR  00000000
PTPortugal                                010Portugal                                ED_MIRROR  00000000
PWPalau                                   825Palau                                    D_MIRROR  00000000
PYParaguay                                520Paraguay                                 D_MIRROR  00000000
QAQatar                                   644Qatar                                    D_MIRROR  00000000
REReunión                                 001Reunión                                  D_MIRROR  00000000
RORumania                                 066Rumania                                 ED_MIRROR  00000000
RSSerbia                                  094Serbia                                   D_MIRROR  00000000
RURusia (Federación de)                   075Rusia (Federación de)                    D_MIRROR  00000000
RWRuanda                                  324Ruanda                                   D_MIRROR  00000000
SAArabia Saudita                          632Arabia Saudita                           D_MIRROR  00000000
SBIslas Salomón                           806Islas Salomón                            D_MIRROR  00000000
SCSeychelles                              355Seychelles                               D_MIRROR  00000000
SDSudan                                   224Sudan                                    D_MIRROR  00000000
SESuecia                                  030Suecia                                  ED_MIRROR  00000000
SGSingapur                                706Singapur                                 D_MIRROR  00000000
SHSaint Helena                            329Saint Helena                             D_MIRROR  00000000
SIEslovenia                               091Eslovenia                               ED_MIRROR  00000000
SJSvalbard and Jan Mayen                  028Svalbard and Jan Mayen                   D_MIRROR  00000000
SKEslovaquía                              063Eslovaquía                              ED_MIRROR  00000000
SLSierra Leona                            264Sierra Leona                             D_MIRROR  00000000
SMSan Marino                              047San Marino                               D_MIRROR  00000000
SNSenegal                                 248Senegal                                  D_MIRROR  00000000
SOSomalia                                 342Somalia                                  D_MIRROR  00000000
SRSurinam                                 492Surinam                                  D_MIRROR  00000000
STSanto Tomé y Principe                   311Santo Tomé y Principe                    D_MIRROR  00000000
SUU.S.S.R.                                056U.R.S.S.                                 PRADASC   20020122
SVEl Salvador                             428El Salvador                              D_MIRROR  00000000
SYSiria                                   608Siria                                    D_MIRROR  00000000
SZSwazilandia                             393Swazilandia                              D_MIRROR  00000000
TATAIWAN, PROVINCE OF CHINA               736TAIWAN                                   VILAJOSANA19951214
TCIslas Turcas y Caicos                   454Islas Turcas y Caicos                    D_MIRROR  00000000
TDChad                                    244Chad                                     D_MIRROR  00000000
TFFRENCH SOUTHERN TERRITORIES             894FRENCH SOUTHERN TERRITORIES              D_MIRROR  00000000
TGTogo                                    280Togo                                     D_MIRROR  00000000
THTailandia                               680Tailandia                                D_MIRROR  00000000
TJTayikistan                              082Tayikistan                               D_MIRROR  00000000
TKTokelau                                 839Tokelau                                  D_MIRROR  00000000
TLTimor-Leste                             626Timor-Leste                              D_MIRROR  00000000
TMTurkmenistan                            080Turkmenistan                             D_MIRROR  00000000
TNTúnez                                   212Túnez                                    D_MIRROR  00000000
TOTonga                                   817Tonga                                    D_MIRROR  00000000
TPEAST TIMOR                              986TIMOR ORIENTAL                           VILAJOES  20050513
TRTurquía                                 052Turquía                                  D_MIRROR  00000000
TTTrinidad y Tobago                       472Trinidad y Tobago                        D_MIRROR  00000000
TUTURKMENISTAN                            080TURKMENISTAN                             VILAJOSANA19951122
TVTuvalu                                  807Tuvalu                                   D_MIRROR  00000000
TWTaiwan                                  736Taiwan                                   D_MIRROR  00000000
TZTanzania                                352Tanzania                                 D_MIRROR  00000000
UAUcrania                                 072Ucrania                                  D_MIRROR  00000000
UGUganda                                  350Uganda                                   D_MIRROR  00000000
UMUNITED STATES MINOR OUTLYING ISLANDS    832UNITED STATES MINOR OUTLYING ISLANDS     D_MIRROR  00000000
USEstados Unidos                          400Estados Unidos                           D_MIRROR  00000000
UYUruguay                                 524Uruguay                                  D_MIRROR  00000000
UZUzbekistan                              081Uzbekistan                               D_MIRROR  00000000
VAHOLY SEE (VATICAN CITY STATE)           045HOLY SEE (VATICAN CITY STATE)            D_MIRROR  00000000
VCSan Vicente                             467San Vicente                              D_MIRROR  00000000
VEVenezuela                               484Venezuela                                D_MIRROR  00000000
VGVirgin Islands, British                 468Virgin Islands, British                  D_MIRROR  00000000
VIIslas Vírgenes (USA)                    457Islas Vírgenes (USA)                     D_MIRROR  00000000
VNVietnam                                 690Vietnam                                  D_MIRROR  00000000
VUVanuatu                                 816Vanuatu                                  D_MIRROR  00000000
WFIslas Wallis y Futuna                   811Islas Wallis y Futuna                    D_MIRROR  00000000
WSSamoa                                   819Samoa                                    D_MIRROR  00000000
XCCEUTA                                   021CEUTA                                    PRADASC   20050513
XKKOSOVO                                  095KOSOVO                                   D_MIRROR  00000000
XPCISJORDANIA/FRANJA DE GAZA              625CISJORDANIA/FRANJA DE GAZA               PRADASC   20050513
XS                                        095KOSOVO                                   D_MIRROR  00000000
XX                                           DESEMB CN 20" LL                         D_MIRROR  00000000
XZInstalaciones en aguas internacionales  958Instalaciones en aguas internacionales   D_MIRROR  00000000
YDYEMEN                                   653YEMEN                                    VILAJOSANA19951214
YEYemen                                   653Yemen                                    D_MIRROR  00000000
YOMAYOTTE                                 377MAYOTTE                                  GRIMALTC  19951214
YTMayotte                                 377Mayotte                                  D_MIRROR  00000000
YUYUGOSLAVIA                              094YUGOSLAVIA                               VILAJOES  20050512
ZASudafrica                               388Sudafrica                                D_MIRROR  00000000
ZMZambia                                  378Zambia                                   D_MIRROR  00000000
ZRZAIRE                                   985ZAIRE (REPUBLICA)                        VILAJOES  20050513
ZWZimbabwe                                382Zimbabwe                                 D_MIRROR  00000000
ZZSin Especificar                         999Sin Especificar                          D_MIRROR  00000000
01UKRAINE                                 072UCRANIA                                  ESCOLANO  19941024
02TUVALU                                  807TUVALU                                   VILAJOSANA19951003
03IRISH REPUBLIC                          998REPUBLICA DE IRLANDA                     VILAJOES  19990713
04ISLE OF MAN                             006ISLA DE MANN                             VILAJOSANA19951215