<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<INVOIC>
    <doc_header>
        <document>INVOIC</document>
        <messagename>380</messagename>
        <function>47</function>
        <sender>ESQ33333333</sender>
        <receiver>ESQ55555555</receiver>
        <timestamp>1807200912</timestamp>
        <application>Factura Telematica</application>
        <format>XML</format>
        <doctype>.</doctype>
    </doc_header>
    <factura>
        <cabecera>
            <numeroMensaje>0APB2017126480</numeroMensaje>
            <numeroDocumento>B2017010058942FRA</numeroDocumento>
            <fechaFactura>20171116</fechaFactura>
            <fechaEnvio>20171116</fechaEnvio>
            <instruccionesPago>
                <condicionesPago>33</condicionesPago>
            </instruccionesPago>
            <descripcionSubpuerto>Barcelona</descripcionSubpuerto>
            <descripcionTarifa>Taxa de les Mercaderies</descripcionTarifa>
            <facturaExentaIVA>EXENTA DE IVA</facturaExentaIVA>
            <numeroDeCarpeta>B20179113 /2017</numeroDeCarpeta>
            <referenciaAdicional>2017 81776</referenciaAdicional>
            <emisorFactura>
                <nombreYDireccion>
                    <nif>Q0867012G</nif>
                    <tipoEntidad>J</tipoEntidad>
                    <nombre>AUTORITAT PORTUARIA DE BARCELONA</nombre>
                    <calle>PORTAL DE LA PAU</calle>
                    <numero>6</numero>
                    <ciudad>BARCELONA</ciudad>
                    <subentidadPais>08</subentidadPais>
                    <codigoPostal>08039</codigoPostal>
                    <paisCodificado>ES</paisCodificado>
                </nombreYDireccion>
                <contacto>
                    <idContacto>AUTORITAT PORTUARIA DE BARCELONA</idContacto>
                </contacto>
            </emisorFactura>
            <receptorFactura>
                <nombreYDireccion>
                    <nif>Q55555555</nif>
                    <tipoEntidad>J</tipoEntidad>
                    <nombre>HAPAG &amp; LLOYD SPAIN SL</nombre>
                    <calle>CONDAL</calle>
                    <tipoVia>C</tipoVia>
                    <numero>32</numero>
                    <ciudad>BARCELONA</ciudad>
                    <subentidadPais>08</subentidadPais>
                    <codigoPostal>08002</codigoPostal>
                    <paisCodificado>ES</paisCodificado>
                </nombreYDireccion>
                <institucionFinanciera>
                    <numeroCuenta>5625314978</numeroCuenta>
                    <codigoEntidadBancaria>0159</codigoEntidadBancaria>
                    <sucursal>0002</sucursal>
                    <codigoPais>ES</codigoPais>
                </institucionFinanciera>
                <contacto>
                    <idContacto>HAPAG &amp; LLOYD SPAIN SL</idContacto>
                    <comunicacion>
                        <numero>3170030</numero>
                        <canal>TE</canal>
                    </comunicacion>
                    <comunicacion>
                        <numero>934122599</numero>
                        <canal>FX</canal>
                    </comunicacion>
                </contacto>
            </receptorFactura>
            <lugarOrigenFactura>
                <nombreYDireccion>
                    <nombre>AUTORITAT PORTUARIA DE BARCELONA</nombre>
                </nombreYDireccion>
                <contacto>
                    <idContacto>AUTORITAT PORTUARIA DE BARCELONA</idContacto>
                </contacto>
            </lugarOrigenFactura>
            <divisaFactura>EUE</divisaFactura>
            <terminosDePago>
                <fechaVencimientoFactura>20180105</fechaVencimientoFactura>
                <tipoIVA>0000000000</tipoIVA>
            </terminosDePago>
            <detallesTransporte>
                <nombreDelBuque>POMERENIA SKY</nombreDelBuque>
                <numeroDeEscala>00000000000000000000000000000081776</numeroDeEscala>
            </detallesTransporte>
            <requerimientoCondicion>
                <idRequerimientoCondicion>DATCAB1</idRequerimientoCondicion>
                <fechaCondicion>201711160000</fechaCondicion>
                <informacionAdicional>9339583 POMERENIA SKY</informacionAdicional>
                <informacionGeneral>Buque IMO</informacionGeneral>
            </requerimientoCondicion>
            <requerimientoCondicion>
                <idRequerimientoCondicion>DATCAB2</idRequerimientoCondicion>
                <fechaCondicion>201711160000</fechaCondicion>
                <informacionGeneral>Periodo impositivo:</informacionGeneral>
            </requerimientoCondicion>
            <requerimientoCondicion>
                <idRequerimientoCondicion>DATCAB3</idRequerimientoCondicion>
                <fechaCondicion>201711160000</fechaCondicion>
                <informacionGeneral>Escala:</informacionGeneral>
            </requerimientoCondicion>
            <requerimientoCondicion>
                <idRequerimientoCondicion>DATCAB4</idRequerimientoCondicion>
                <fechaCondicion>201711160000</fechaCondicion>
                <informacionAdicional>000086 HAPAG &amp; LLOYD SPAIN SL Q55555555</informacionAdicional>
                <informacionGeneral>Consignatario</informacionGeneral>
            </requerimientoCondicion>
            <requerimientoCondicion>
                <idRequerimientoCondicion>DATCAB5</idRequerimientoCondicion>
                <fechaCondicion>201711160000</fechaCondicion>
                <informacionAdicional>10/11/2017 00:02</informacionAdicional>
                <informacionGeneral>Fecha/Hora entrada buque:</informacionGeneral>
            </requerimientoCondicion>
            <requerimientoCondicion>
                <idRequerimientoCondicion>DATCAB6</idRequerimientoCondicion>
                <fechaCondicion>201711160000</fechaCondicion>
                <informacionGeneral>Tipo manifiesto</informacionGeneral>
            </requerimientoCondicion>
            <requerimientoCondicion>
                <idRequerimientoCondicion>DATCAB7</idRequerimientoCondicion>
                <fechaCondicion>201711160000</fechaCondicion>
                <informacionAdicional>250 MED AMERICA</informacionAdicional>
                <informacionGeneral>Línea serv./regular</informacionGeneral>
            </requerimientoCondicion>
            <requerimientoCondicion>
                <idRequerimientoCondicion>DATCAB8</idRequerimientoCondicion>
                <fechaCondicion>201711160000</fechaCondicion>
                <informacionAdicional>10/11/2017 17:58</informacionAdicional>
                <informacionGeneral>Fecha hora salida de buque</informacionGeneral>
            </requerimientoCondicion>
            <requerimientoCondicion>
                <idRequerimientoCondicion>DATCAB9</idRequerimientoCondicion>
                <fechaCondicion>201711160000</fechaCondicion>
                <informacionAdicional>S Simplificado</informacionAdicional>
                <informacionGeneral>Régimen</informacionGeneral>
            </requerimientoCondicion>
            <requerimientoCondicion>
                <idRequerimientoCondicion>DATCAB10</idRequerimientoCondicion>
                <fechaCondicion>201711160000</fechaCondicion>
                <informacionAdicional>44 HAPAG &amp; LLOYD,A.G.</informacionAdicional>
                <informacionGeneral>Armador</informacionGeneral>
            </requerimientoCondicion>
            <requerimientoCondicion>
                <idRequerimientoCondicion>DATCAB11</idRequerimientoCondicion>
                <fechaCondicion>201711160000</fechaCondicion>
                <informacionAdicional>Portacontenidors</informacionAdicional>
                <informacionGeneral>Tipo de buque</informacionGeneral>
            </requerimientoCondicion>
            <requerimientoCondicion>
                <idRequerimientoCondicion>DATCAB12</idRequerimientoCondicion>
                <fechaCondicion>201711160000</fechaCondicion>
                <informacionAdicional>S</informacionAdicional>
                <informacionGeneral>Servicio regular</informacionGeneral>
            </requerimientoCondicion>
            <requerimientoCondicion>
                <idRequerimientoCondicion>LITREF1</idRequerimientoCondicion>
                <fechaCondicion>201711160000</fechaCondicion>
                <informacionGeneral>Elemento de transporte/operación/presentación</informacionGeneral>
            </requerimientoCondicion>
            <requerimientoCondicion>
                <idRequerimientoCondicion>UNIDAD1</idRequerimientoCondicion>
                <fechaCondicion>201711160000</fechaCondicion>
                <informacionGeneral>N?. Unidades</informacionGeneral>
            </requerimientoCondicion>
            <requerimientoCondicion>
                <idRequerimientoCondicion>PRECIO</idRequerimientoCondicion>
                <fechaCondicion>201711160000</fechaCondicion>
                <informacionGeneral>Cuota tasas</informacionGeneral>
            </requerimientoCondicion>
            <requerimientoCondicion>
                <idRequerimientoCondicion>IMPORTE</idRequerimientoCondicion>
                <fechaCondicion>201711160000</fechaCondicion>
                <informacionGeneral>Importe</informacionGeneral>
            </requerimientoCondicion>
            <requerimientoCondicion>
                <idRequerimientoCondicion>PORCENT</idRequerimientoCondicion>
                <fechaCondicion>201711160000</fechaCondicion>
                <informacionGeneral>Porcentaje</informacionGeneral>
            </requerimientoCondicion>
        </cabecera>
        <detalles>
            <detalle>
                <numeroLinea>1</numeroLinea>
                <descripcionArticulo>
                    <tipoDescripcion>B</tipoDescripcion>
                    <codigoCaracteristicaArticulo>C06</codigoCaracteristicaArticulo>
                    <descripcionArticulo1>Desembarq CN 20' Bu. Term. Conc.</descripcionArticulo1>
                </descripcionArticulo>
                <cantidad>
                    <calificadorCantidad>ZU1</calificadorCantidad>
                    <valorCantidad>000000000001,00</valorCantidad>
                </cantidad>
                <infoAdicional>
                    <texto1>E/D contenedores vac?os (Art.245)</texto1>
                </infoAdicional>
                <precioUnitario>
                    <importe>0000000000002,1240</importe>
                    <divisa>EUE</divisa>
                </precioUnitario>
                <precioLinea>
                    <importe>000000000000056,03</importe>
                    <divisa>EUE</divisa>
                </precioLinea>
                <importeLinea>
                    <importe>000000000000001,27</importe>
                    <divisa>EUE</divisa>
                </importeLinea>
            </detalle>
            <detalle>
                <numeroLinea>2</numeroLinea>
                <descripcionArticulo>
                    <tipoDescripcion>B</tipoDescripcion>
                    <codigoCaracteristicaArticulo>C16</codigoCaracteristicaArticulo>
                    <descripcionArticulo1>Desembarq CN 20' Pl. Term. Conc.</descripcionArticulo1>
                </descripcionArticulo>
                <cantidad>
                    <calificadorCantidad>ZU1</calificadorCantidad>
                    <valorCantidad>000000000004,00</valorCantidad>
                </cantidad>
                <infoAdicional>
                    <texto1>Carretera (Art.245)</texto1>
                </infoAdicional>
                <precioUnitario>
                    <importe>0000000000023,6000</importe>
                    <divisa>EUE</divisa>
                </precioUnitario>
                <precioLinea>
                    <importe>000000000000056,03</importe>
                    <divisa>EUE</divisa>
                </precioLinea>
                <importeLinea>
                    <importe>000000000000093,38</importe>
                    <divisa>EUE</divisa>
                </importeLinea>
            </detalle>
            <detalle>
                <numeroLinea>3</numeroLinea>
                <descripcionArticulo>
                    <tipoDescripcion>B</tipoDescripcion>
                    <codigoCaracteristicaArticulo>C18</codigoCaracteristicaArticulo>
                    <descripcionArticulo1>Desembarq CN 40' Pl. Term. Conc.</descripcionArticulo1>
                </descripcionArticulo>
                <cantidad>
                    <calificadorCantidad>ZU1</calificadorCantidad>
                    <valorCantidad>000000000004,00</valorCantidad>
                </cantidad>
                <infoAdicional>
                    <texto1>Carretera  (Art.245)</texto1>
                </infoAdicional>
                <precioUnitario>
                    <importe>0000000000035,4000</importe>
                    <divisa>EUE</divisa>
                </precioUnitario>
                <precioLinea>
                    <importe>000000000000056,03</importe>
                    <divisa>EUE</divisa>
                </precioLinea>
                <importeLinea>
                    <importe>000000000000140,07</importe>
                    <divisa>EUE</divisa>
                </importeLinea>
            </detalle>
        </detalles>
        <resumen>
            <importeBruto>
                <importe>000000000000234,72</importe>
                <divisa>EUE</divisa>
            </importeBruto>
            <importeNeto>
                <importe>000000000000234,72</importe>
                <divisa>EUE</divisa>
            </importeNeto>
            <impuesto>
                <tipoTasa>VAT</tipoTasa>
                <importeTasa>
                    <importe>000000000000000000</importe>
                    <divisa>EUE</divisa>
                </importeTasa>
            </impuesto>
        </resumen>
    </factura>
</INVOIC>
